(function(global){
'use strict';
const AP=global.AssistaPay=global.AssistaPay||{};
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
function when(value){const date=new Date(value);return Number.isNaN(date.getTime())?'':date.toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'});}
function renderHistory(container){const rows=AP.accountHistory?.all?.()||[];container.innerHTML=`<main class="ap-settings-page"><header class="ap-settings-header"><a href="app.html?view=profile" aria-label="Voltar">‹</a><h1>Histórico da conta</h1><button type="button" data-clear-history aria-label="Limpar histórico">🗑</button></header><section class="ap-settings-card"><p>Este histórico reúne as ações realizadas nesta conta dentro do AssistaPay, como páginas abertas, botões usados e alterações de perfil.</p></section><section class="ap-history-list">${rows.length?rows.map(item=>`<article><div><strong>${esc(item.label)}</strong>${item.details?`<p>${esc(item.details)}</p>`:''}<small>${esc(when(item.createdAt))}</small></div></article>`).join(''):'<div class="ap-history-empty"><strong>Nenhuma atividade registrada</strong><span>As próximas ações da conta aparecerão aqui.</span></div>'}</section></main>`;container.querySelector('[data-clear-history]')?.addEventListener('click',()=>{if(confirm('Limpar todo o histórico desta conta?')){AP.accountHistory?.clear?.();renderHistory(container);}});}
function renderStoryArchive(container){const rows=AP.storyArchive?.all?.()||[];container.innerHTML=`<main class="ap-settings-page"><header class="ap-settings-header"><a href="app.html?view=settings" aria-label="Voltar">‹</a><h1>Arquivo de Stories</h1><button type="button" data-clear-stories aria-label="Limpar arquivo">🗑</button></header><section class="ap-settings-card"><p>Arquivo privado do dono da conta. Stories deixam de aparecer publicamente após 24 horas, mas continuam disponíveis aqui.</p></section><section class="ap-story-archive-grid">${rows.length?rows.map(item=>`<article data-story-id="${esc(item.id)}"><button type="button" data-open-story>${String(item.mediaType||'').startsWith('video/')?`<video src="${esc(item.media||item.mediaBlob||'')}" muted playsinline preload="metadata"></video>`:`<img src="${esc(item.media||item.mediaBlob||'')}" alt="Story arquivado">`}<span>${esc(when(item.createdAt))}</span></button><button type="button" data-remove-story aria-label="Excluir story">Excluir</button></article>`).join(''):'<div class="ap-history-empty"><strong>Nenhum story arquivado</strong><span>Os stories publicados aparecerão aqui.</span></div>'}</section></main>`;container.querySelectorAll('[data-open-story]').forEach(button=>button.addEventListener('click',()=>{const id=button.closest('[data-story-id]')?.dataset.storyId;const story=rows.find(item=>String(item.id)===String(id));AP.avatarStory?.open?.(story);}));container.querySelectorAll('[data-remove-story]').forEach(button=>button.addEventListener('click',()=>{const id=button.closest('[data-story-id]')?.dataset.storyId;if(confirm('Excluir este story do arquivo?')){AP.storyArchive?.remove?.(id);renderStoryArchive(container);}}));container.querySelector('[data-clear-stories]')?.addEventListener('click',()=>{if(confirm('Limpar todo o arquivo de stories?')){AP.storyArchive?.clear?.();renderStoryArchive(container);}});}
function render(container){container.innerHTML=`<main class="ap-settings-page"><header class="ap-settings-header"><a href="app.html?view=profile" aria-label="Voltar">‹</a><h1>Configurações</h1><span></span></header><section class="ap-settings-card"><h2>Conta</h2><a href="app.html?view=account-history"><span>◷</span><div><strong>Histórico da conta</strong><small>Veja as atividades realizadas no AssistaPay</small></div><em>›</em></a></section><section class="ap-settings-card"><h2>Conteúdo</h2><a href="app.html?view=story-archive"><span>◉</span><div><strong>Arquivo de Stories</strong><small>Veja seus stories antigos em um espaço privado</small></div><em>›</em></a></section></main>`;}
AP.settingsUI=Object.freeze({render,renderHistory,renderStoryArchive});
})(window);
