(function(global){
'use strict';
const AP=global.AssistaPay=global.AssistaPay||{};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const when=v=>new Date(v).toLocaleString('pt-BR');
const stories=()=>{try{return JSON.parse(localStorage.getItem('ap:story-archive')||'[]');}catch{return [];}};
function renderHistory(container){const rows=AP.accountHistory?.all?.()||[];container.innerHTML=`<main class="ap-settings-page"><header class="ap-settings-header"><a href="app.html?view=profile">‹</a><h1>Histórico da conta</h1><button data-clear-history>🗑</button></header><section class="ap-history-list">${rows.length?rows.map(x=>`<article><strong>${esc(x.label)}</strong><p>${esc(x.details||'')}</p><small>${esc(when(x.createdAt))}</small></article>`).join(''):'<div class="ap-history-empty">Nenhuma atividade registrada</div>'}</section></main>`;container.querySelector('[data-clear-history]')?.addEventListener('click',()=>{AP.accountHistory?.clear?.();renderHistory(container);});}
function renderStoryArchive(container){const rows=stories();container.innerHTML=`<main class="ap-settings-page"><header class="ap-settings-header"><a href="app.html?view=settings">‹</a><h1>Arquivo de Stories</h1><button data-clear-stories>🗑</button></header><section class="ap-settings-card"><p>Arquivo privado. O story público expira em 24 horas.</p></section><section class="ap-story-archive-grid">${rows.length?rows.map(x=>`<article>${String(x.mediaType||'').startsWith('video/')?`<video src="${esc(x.media||x.mediaBlob)}" controls></video>`:`<img src="${esc(x.media||x.mediaBlob)}" alt="Story">`}<small>${esc(when(x.createdAt))}</small></article>`).join(''):'<div class="ap-history-empty">Nenhum story arquivado</div>'}</section></main>`;container.querySelector('[data-clear-stories]')?.addEventListener('click',()=>{localStorage.removeItem('ap:story-archive');renderStoryArchive(container);});}
function render(container){if(new URLSearchParams(location.search).get('section')==='story-archive')return renderStoryArchive(container);container.innerHTML=`<main class="ap-settings-page"><header class="ap-settings-header"><a href="app.html?view=profile">‹</a><h1>Configurações</h1><span></span></header><section class="ap-settings-card"><h2>Conta</h2><a href="app.html?view=account-history"><span>◷</span><div><strong>Histórico da conta</strong><small>Atividades realizadas no AssistaPay</small></div><em>›</em></a></section><section class="ap-settings-card"><h2>Conteúdo</h2><a href="app.html?view=settings&section=story-archive"><span>◉</span><div><strong>Arquivo de Stories</strong><small>Stories antigos da sua conta</small></div><em>›</em></a></section></main>`;}
AP.settingsUI=Object.freeze({render,renderHistory,renderStoryArchive});
})(window);
