(function(global){
  'use strict';
  const AP=global.AssistaPay=global.AssistaPay||{};
  const discovery=[
    {id:'v1',title:'Rotina de skincare',views:'107 mil',category:'Beleza',image:'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=600&q=80'},
    {id:'v2',title:'Tecnologia que facilita',views:'42,2 mil',category:'Tecnologia',image:'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=600&q=80'},
    {id:'v3',title:'Treino rápido em casa',views:'31 mil',category:'Fitness',image:'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=600&q=80'},
    {id:'v4',title:'Casa organizada',views:'25,7 mil',category:'Casa',image:'https://images.unsplash.com/photo-1556912167-f556f1f39fdf?auto=format&fit=crop&w=600&q=80'},
    {id:'v5',title:'Receita prática',views:'90,9 mil',category:'Comida',image:'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=600&q=80'},
    {id:'v6',title:'Moda para o dia a dia',views:'25 mil',category:'Moda',image:'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=600&q=80'},
    {id:'v7',title:'Acessórios em alta',views:'27 mil',category:'Moda',image:'https://images.unsplash.com/photo-1617038220319-276d3cfab638?auto=format&fit=crop&w=600&q=80'},
    {id:'v8',title:'Fone Bluetooth Pro',views:'44 mil',category:'Tecnologia',image:'https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?auto=format&fit=crop&w=600&q=80'},
    {id:'v9',title:'Ideias para sua loja',views:'32 mil',category:'Negócios',image:'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=600&q=80'},
    {id:'v10',title:'Viagem inesquecível',views:'18 mil',category:'Viagem',image:'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=600&q=80'},
    {id:'v11',title:'Decoração simples',views:'36 mil',category:'Casa',image:'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=600&q=80'},
    {id:'v12',title:'Maquiagem leve',views:'29 mil',category:'Beleza',image:'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=600&q=80'}
  ];
  const products=[
    {id:'fone-bluetooth',name:'Fone Bluetooth Pro',price:'R$ 129,90',store:'Tech Store',image:'https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?auto=format&fit=crop&w=600&q=80'},
    {id:'kit-skincare',name:'Kit Skincare Completo',price:'R$ 129,90',store:'Bella Care',image:'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?auto=format&fit=crop&w=600&q=80'},
    {id:'smartwatch-x1',name:'Smartwatch X1',price:'R$ 199,90',store:'Tech Store',image:'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=600&q=80'},
    {id:'air-fryer',name:'Air Fryer 5L',price:'R$ 299,90',store:'Casa Fácil',image:'https://images.unsplash.com/photo-1585515320310-259814833e62?auto=format&fit=crop&w=600&q=80'}
  ];
  function normalize(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();}
  function formatFollowers(value){if(value>=1000000)return `${(value/1000000).toFixed(1).replace('.',',')} mi`;if(value>=1000)return `${(value/1000).toFixed(value>=100000?0:1).replace('.',',')} mil`;return String(value);}
  function nav(){return `<nav class="ap-page-nav ap-search-nav"><a href="feed.html"><span>⌂</span>Início</a><a href="app.html?view=search" class="active"><span>⌕</span>Pesquisar</a><a href="app.html?view=create" class="create"><span>+</span></a><a href="app.html?view=shop"><span>▱</span>Shop</a><a href="app.html?view=profile"><span>♙</span>Perfil</a></nav>`;}
  function userCard(user){const following=AP.searchStore.isFollowing(user.id);return `<article class="ap-search-user"><button class="ap-search-user-main" data-open-user="${user.id}"><img src="${user.avatar}" alt="${user.name}"><div><strong>${user.name}${user.verified?' <span class="ap-search-verified">✓</span>':''}</strong><small>${user.username}</small><p>${user.type} · ${user.category}</p><span>${formatFollowers(user.followers)} seguidores</span></div></button><button class="ap-search-follow ${following?'following':''}" data-follow-user="${user.id}">${following?'Seguindo':'Seguir'}</button></article>`;}
  function renderVideos(term){const q=normalize(term);const items=discovery.filter(item=>!q||normalize(`${item.title} ${item.category}`).includes(q));return items.length?`<div class="ap-discovery-grid">${items.map(item=>`<button class="ap-discovery-card" data-video-result="${item.id}"><img src="${item.image}" alt="${item.title}"><span>◉ ${item.views}</span><strong>${item.title}</strong></button>`).join('')}</div>`:empty('Nenhum vídeo encontrado');}
  function renderPeople(term){const users=AP.searchService.search(term);return users.length?`<div class="ap-search-people">${users.map(userCard).join('')}</div>`:empty('Nenhuma pessoa encontrada');}
  function renderProducts(term){const q=normalize(term);const items=products.filter(item=>!q||normalize(`${item.name} ${item.store}`).includes(q));return items.length?`<div class="ap-search-product-grid">${items.map(item=>`<button data-product-result="${item.id}"><img src="${item.image}" alt="${item.name}"><strong>${item.name}</strong><small>${item.store}</small><b>${item.price}</b></button>`).join('')}</div>`:empty('Nenhum produto encontrado');}
  function renderStores(term){const q=normalize(term);const stores=AP.searchService.users.filter(user=>user.type==='Loja'&&(!q||normalize(`${user.name} ${user.category}`).includes(q)));return stores.length?`<div class="ap-search-people">${stores.map(userCard).join('')}</div>`:empty('Nenhuma loja encontrada');}
  function empty(text){return `<div class="ap-search-empty"><span>⌕</span><h3>${text}</h3><p>Tente pesquisar por outro termo.</p></div>`;}
  function renderContent(container){const tab=container.querySelector('.ap-search-tabs .active')?.dataset.searchTab||'videos';const term=container.querySelector('#apUserSearchInput').value.trim();const host=container.querySelector('#apSearchResults');host.innerHTML=tab==='people'?renderPeople(term):tab==='products'?renderProducts(term):tab==='stores'?renderStores(term):renderVideos(term);}
  function renderHistory(container){const history=AP.searchStore.history();const section=container.querySelector('#apSearchHistory');section.innerHTML=history.length?`<header><h2>Pesquisas recentes</h2><button data-clear-search-history>Limpar</button></header><div>${history.map(item=>`<button data-history-term="${item.replace(/"/g,'&quot;')}">↺ ${item}</button>`).join('')}</div>`:'';}
  function render(container){container.innerHTML=`<main class="ap-search-page"><div class="ap-search-sticky"><div class="ap-search-field"><span>⌕</span><input id="apUserSearchInput" type="search" autocomplete="off" placeholder="Pesquisar"><button id="apSearchClear" type="button">×</button></div><nav class="ap-search-tabs"><button class="active" data-search-tab="videos">Vídeos</button><button data-search-tab="people">Pessoas</button><button data-search-tab="products">Produtos</button><button data-search-tab="stores">Lojas</button></nav></div><section id="apSearchHistory" class="ap-search-history"></section><section id="apSearchResults"></section></main>${nav()}<div class="ap-search-profile" id="apSearchProfile" aria-hidden="true"></div>`;renderHistory(container);renderContent(container);bind(container);}
  function openProfile(container,id){const user=AP.searchService.getById(id);if(!user)return;AP.searchStore.addHistory(user.username);renderHistory(container);const following=AP.searchStore.isFollowing(id);const host=container.querySelector('#apSearchProfile');host.innerHTML=`<main><header><button data-close-user-profile>‹</button><h2>Perfil</h2><span></span></header><section><img src="${user.avatar}" alt="${user.name}"><h1>${user.name}${user.verified?' <span class="ap-search-verified">✓</span>':''}</h1><small>${user.username}</small><p>${user.bio}</p><div class="ap-search-profile-stats"><span><b>${formatFollowers(user.followers)}</b><small>Seguidores</small></span><span><b>128</b><small>Publicações</small></span><span><b>${user.type}</b><small>Conta</small></span></div><button class="ap-search-profile-follow ${following?'following':''}" data-follow-user="${user.id}">${following?'Seguindo':'Seguir'}</button></section><div class="ap-search-profile-grid">${discovery.slice(0,6).map(item=>`<article><img src="${item.image}" alt=""></article>`).join('')}</div></main>`;host.classList.add('open');host.setAttribute('aria-hidden','false');}
  function closeProfile(container){const host=container.querySelector('#apSearchProfile');host.classList.remove('open');host.setAttribute('aria-hidden','true');}
  function updateFollowButtons(container,id,following){container.querySelectorAll(`[data-follow-user="${CSS.escape(id)}"]`).forEach(button=>{button.textContent=following?'Seguindo':'Seguir';button.classList.toggle('following',following);});}
  function bind(container){const input=container.querySelector('#apUserSearchInput');let timer;input.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(()=>renderContent(container),100);container.querySelector('#apSearchClear').classList.toggle('show',!!input.value);});input.addEventListener('keydown',event=>{if(event.key==='Enter'){const term=input.value.trim();AP.searchStore.addHistory(term);renderHistory(container);renderContent(container);input.blur();}});container.addEventListener('click',event=>{const tab=event.target.closest('[data-search-tab]');if(tab){container.querySelectorAll('[data-search-tab]').forEach(btn=>btn.classList.remove('active'));tab.classList.add('active');renderContent(container);}if(event.target.closest('#apSearchClear')){input.value='';container.querySelector('#apSearchClear').classList.remove('show');renderContent(container);input.focus();}const history=event.target.closest('[data-history-term]');if(history){input.value=history.dataset.historyTerm;renderContent(container);input.focus();}if(event.target.closest('[data-clear-search-history]')){AP.searchStore.clearHistory();renderHistory(container);}const follow=event.target.closest('[data-follow-user]');if(follow){event.stopPropagation();const following=AP.searchStore.toggleFollow(follow.dataset.followUser);updateFollowButtons(container,follow.dataset.followUser,following);}const open=event.target.closest('[data-open-user]');if(open)openProfile(container,open.dataset.openUser);if(event.target.closest('[data-close-user-profile]'))closeProfile(container);const product=event.target.closest('[data-product-result]');if(product)global.location.href=`app.html?view=product&product=${encodeURIComponent(product.dataset.productResult)}`;const video=event.target.closest('[data-video-result]');if(video)global.location.href='feed.html';});}
  AP.searchUI=Object.freeze({render});
})(window);