(function(global){
  'use strict';
  const AP=global.AssistaPay=global.AssistaPay||{};
  function formatFollowers(value){if(value>=1000000)return `${(value/1000000).toFixed(1).replace('.',',')} mi`;if(value>=1000)return `${(value/1000).toFixed(value>=100000?0:1).replace('.',',')} mil`;return String(value);}
  function nav(){return `<nav class="ap-page-nav"><a href="feed.html"><span>⌂</span>Início</a><a href="app.html?view=shop"><span>▱</span>Shop</a><a href="app.html?view=create" class="create"><span>+</span></a><a href="app.html?view=search" class="active"><span>⌕</span>Buscar</a><a href="app.html?view=profile"><span>♙</span>Perfil</a></nav>`;}
  function userCard(user){const following=AP.searchStore.isFollowing(user.id);return `<article class="ap-search-user" data-user-id="${user.id}"><button class="ap-search-user-main" data-open-user="${user.id}"><img src="${user.avatar}" alt="${user.name}"><div><strong>${user.name}${user.verified?' <span class="ap-search-verified">✓</span>':''}</strong><small>${user.username}</small><p>${user.type} · ${user.category}</p><span>${formatFollowers(user.followers)} seguidores</span></div></button><button class="ap-search-follow ${following?'following':''}" data-follow-user="${user.id}">${following?'Seguindo':'Seguir'}</button></article>`;}
  function renderResults(container,term){const host=container.querySelector('#apSearchResults');const results=AP.searchService.search(term);host.innerHTML=results.length?results.map(userCard).join(''):'<div class="ap-search-empty"><span>⌕</span><h3>Nenhum usuário encontrado</h3><p>Tente buscar por outro nome, @usuário ou categoria.</p></div>';container.querySelector('#apSearchResultTitle').textContent=term?`Resultados para “${term}”`:'Sugestões para você';}
  function renderHistory(container){const history=AP.searchStore.history();const section=container.querySelector('#apSearchHistory');section.innerHTML=history.length?`<header><h2>Pesquisas recentes</h2><button data-clear-search-history>Limpar</button></header><div>${history.map(item=>`<button data-history-term="${item.replace(/"/g,'&quot;')}">↺ ${item}</button>`).join('')}</div>`:'';}
  function render(container){container.innerHTML=`<main class="ap-page ap-search-page"><header class="ap-page-header"><a href="feed.html">‹</a><h1>Buscar</h1><span></span></header><div class="ap-search-field"><span>⌕</span><input id="apUserSearchInput" type="search" autocomplete="off" placeholder="Nome, @usuário, loja ou categoria"><button id="apSearchClear" type="button">×</button></div><section id="apSearchHistory" class="ap-search-history"></section><section class="ap-search-results"><h2 id="apSearchResultTitle">Sugestões para você</h2><div id="apSearchResults"></div></section></main>${nav()}<div class="ap-search-profile" id="apSearchProfile" aria-hidden="true"></div>`;renderHistory(container);renderResults(container,'');bind(container);}
  function openProfile(container,id){const user=AP.searchService.getById(id);if(!user)return;AP.searchStore.addHistory(user.username);renderHistory(container);const following=AP.searchStore.isFollowing(id);const host=container.querySelector('#apSearchProfile');host.innerHTML=`<main><header><button data-close-user-profile>‹</button><h2>Perfil</h2><span></span></header><section><img src="${user.avatar}" alt="${user.name}"><h1>${user.name}${user.verified?' <span class="ap-search-verified">✓</span>':''}</h1><small>${user.username}</small><p>${user.bio}</p><div class="ap-search-profile-stats"><span><b>${formatFollowers(user.followers)}</b><small>Seguidores</small></span><span><b>128</b><small>Publicações</small></span><span><b>${user.type}</b><small>Conta</small></span></div><button class="ap-search-profile-follow ${following?'following':''}" data-follow-user="${user.id}">${following?'Seguindo':'Seguir'}</button></section><div class="ap-search-profile-grid"><article></article><article></article><article></article><article></article><article></article><article></article></div></main>`;host.classList.add('open');host.setAttribute('aria-hidden','false');}
  function closeProfile(container){const host=container.querySelector('#apSearchProfile');host.classList.remove('open');host.setAttribute('aria-hidden','true');}
  function updateFollowButtons(container,id,following){container.querySelectorAll(`[data-follow-user="${CSS.escape(id)}"]`).forEach(button=>{button.textContent=following?'Seguindo':'Seguir';button.classList.toggle('following',following);});}
  function bind(container){const input=container.querySelector('#apUserSearchInput');let timer;input.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(()=>renderResults(container,input.value.trim()),120);container.querySelector('#apSearchClear').classList.toggle('show',!!input.value);});input.addEventListener('search',()=>renderResults(container,input.value.trim()));input.addEventListener('keydown',event=>{if(event.key==='Enter'){const term=input.value.trim();AP.searchStore.addHistory(term);renderHistory(container);renderResults(container,term);input.blur();}});container.addEventListener('click',event=>{if(event.target.closest('#apSearchClear')){input.value='';container.querySelector('#apSearchClear').classList.remove('show');renderResults(container,'');input.focus();}const history=event.target.closest('[data-history-term]');if(history){input.value=history.dataset.historyTerm;renderResults(container,input.value);input.focus();}if(event.target.closest('[data-clear-search-history]')){AP.searchStore.clearHistory();renderHistory(container);}const follow=event.target.closest('[data-follow-user]');if(follow){event.stopPropagation();const following=AP.searchStore.toggleFollow(follow.dataset.followUser);updateFollowButtons(container,follow.dataset.followUser,following);}const open=event.target.closest('[data-open-user]');if(open)openProfile(container,open.dataset.openUser);if(event.target.closest('[data-close-user-profile]'))closeProfile(container);});}
  AP.searchUI=Object.freeze({render});
})(window);