(function(global){
  'use strict';
  const AP=global.AssistaPay=global.AssistaPay||{};

  const demoItems=[
    {id:'demo_1',creator:'@bea.beauty',bio:'Beleza, skincare e autocuidado.',avatar:'https://i.pravatar.cc/96?img=47',caption:'Sérum Facial Hidratante. Resultado incrível ✨ #skincare #beleza',category:'Beleza',media:'https://storage.googleapis.com/coverr-main/mp4/Mt_Baker.mp4',likes:'12,3K',comments:'872',shares:'1,2K',saves:'892',product:{title:'Sérum Facial 30ml',price:'R$ 89,90',oldPrice:'R$ 119,90',discount:'-25%',rating:'4,9',sold:'5,2K vendidos',image:'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?auto=format&fit=crop&w=200&q=80'}},
    {id:'demo_2',creator:'@carros.e.motores',bio:'Carros, motores e liberdade sobre rodas.',avatar:'https://i.pravatar.cc/96?img=13',caption:'Nada como liberdade sobre quatro rodas. 🔥🏁 #carros #lifestyle',category:'Automóveis',media:'https://storage.googleapis.com/coverr-main/mp4/Footboys.mp4',likes:'25,7K',comments:'512',shares:'2,1K',saves:'1,3K',product:{title:'Mini Aspirador Portátil',price:'R$ 159,90',oldPrice:'R$ 229,90',discount:'-30%',rating:'4,8',sold:'8,7K vendidos',image:'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=200&q=80'}},
    {id:'demo_3',creator:'@casa.pratica',bio:'Ideias simples para uma casa mais prática.',avatar:'https://i.pravatar.cc/96?img=14',caption:'Uma ideia simples para deixar a casa mais organizada. ✨ #casa #organização',category:'Casa',media:'https://storage.googleapis.com/coverr-main/mp4/Night-Traffic.mp4',likes:'8,4K',comments:'204',shares:'630',saves:'411',product:{title:'Organizador Multiuso',price:'R$ 49,90',oldPrice:'R$ 69,90',discount:'-29%',rating:'4,7',sold:'5,2K vendidos',image:'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=200&q=80'}}
  ];

  function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
  function slideTemplate(item,index){const p=item.product||{};return `<article class="ap-video-slide" data-id="${esc(item.id)}" data-category="${esc(item.category)}">
    <video src="${esc(item.media)}" playsinline muted loop preload="${index<2?'auto':'metadata'}" ${index===0?'autoplay':''}></video>
    <div class="ap-like-burst" aria-hidden="true">♥</div><div class="ap-play-indicator" aria-hidden="true">▶</div>
    <button class="ap-sound-toggle" data-action="sound" aria-label="Ativar ou desativar som">🔇</button>
    <div class="ap-feed-top"><button class="ap-menu-icon" aria-label="Menu">☰</button><div class="ap-feed-tabs"><button class="active">Para você</button><button>Descobrir</button></div><button class="ap-more" aria-label="Mais opções">⋮</button></div>
    <aside class="ap-actions">
      <div class="ap-action"><button data-action="like" aria-label="Curtir">♥</button><small>${esc(item.likes)}</small></div>
      <div class="ap-action"><button data-action="comment" aria-label="Comentar">●</button><small>${esc(item.comments)}</small></div>
      <div class="ap-action"><button data-action="share" aria-label="Compartilhar">↗</button><small>${esc(item.shares)}</small></div>
      <div class="ap-avatar-wrap"><button class="ap-avatar-button" data-action="creator"><img class="ap-avatar" src="${esc(item.avatar)}" alt="Perfil de ${esc(item.creator)}"></button><button data-action="follow" class="ap-follow">+</button></div>
    </aside>
    <div class="ap-caption"><button class="ap-creator-name" data-action="creator"><strong>${esc(item.creator)} <span class="ap-verified">✓</span></strong></button><p>${esc(item.caption)}</p></div>
    <button class="ap-product-strip" data-action="product" type="button"><img src="${esc(p.image)}" alt="${esc(p.title)}"><span class="ap-product-copy"><strong>${esc(p.title)}</strong><span class="ap-price-row"><b>${esc(p.price)}</b></span></span><span class="ap-product-arrow">›</span></button>
  </article>`;}

  function setLiked(slide,liked){const button=slide.querySelector('[data-action="like"]');button.textContent=liked?'♥':'♡';button.classList.toggle('liked',liked);slide.dataset.liked=liked?'1':'0';}
  function showBurst(slide){const burst=slide.querySelector('.ap-like-burst');burst.classList.remove('show');void burst.offsetWidth;burst.classList.add('show');}
  function showPlayState(slide,paused){const indicator=slide.querySelector('.ap-play-indicator');indicator.textContent=paused?'▶':'❚❚';indicator.classList.remove('show');void indicator.offsetWidth;indicator.classList.add('show');}
  function preloadNext(slide){const next=slide.nextElementSibling?.querySelector('video');if(next&&next.preload!=='auto'){next.preload='auto';next.load();}}
  function render(container,items=demoItems){container.innerHTML=items.map(slideTemplate).join('');bind(container,items);observe(container);}
  function bind(container,items){let lastTap=0;container.addEventListener('click',event=>{const slide=event.target.closest('.ap-video-slide');if(!slide)return;const button=event.target.closest('[data-action]');const video=slide.querySelector('video');if(!button){const now=Date.now();if(now-lastTap<320){setLiked(slide,true);showBurst(slide);AP.events?.emit('feed:like',{contentId:slide.dataset.id,source:'double-tap'});}else{if(video.paused){video.play().catch(()=>{});showPlayState(slide,false);}else{video.pause();showPlayState(slide,true);}}lastTap=now;return;}const action=button.dataset.action;const item=items.find(entry=>entry.id===slide.dataset.id);if(action==='like'){setLiked(slide,slide.dataset.liked!=='1');}if(action==='sound'){video.muted=!video.muted;button.textContent=video.muted?'🔇':'🔊';}if(action==='follow'){button.textContent=button.textContent==='✓'?'+':'✓';}if(action==='creator'){AP.feedSheets?.openCreator({name:item?.creator,avatar:item?.avatar,bio:item?.bio});}if(action==='comment'){AP.feedSheets?.openComments();}if(action==='product'){AP.feedSheets?.openProduct(item?.product||{});}if(action==='share'&&navigator.share){navigator.share({title:'AssistaPay',text:'Veja este vídeo no AssistaPay'}).catch(()=>{});}AP.events?.emit(`feed:${action}`,{contentId:slide.dataset.id,category:slide.dataset.category});});}
  function observe(container){const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{const video=entry.target.querySelector('video');if(entry.isIntersecting&&entry.intersectionRatio>.72){container.querySelectorAll('video').forEach(item=>{if(item!==video)item.pause();});video?.play().catch(()=>{});preloadNext(entry.target);AP.events?.emit('feed:view',{contentId:entry.target.dataset.id,category:entry.target.dataset.category});}else video?.pause();});},{threshold:[.72]});container.querySelectorAll('.ap-video-slide').forEach(slide=>observer.observe(slide));}
  AP.feedUI=Object.freeze({render,demoItems});
})(window);