(function(global){
  'use strict';
  const AP=global.AssistaPay=global.AssistaPay||{};
  const SOCIAL_KEY='ap:social';
  const FOLLOW_KEY='ap:follows';
  const FEED_COMPATIBILITY='feed:view double-tap data-action="save" openProduct';
  let currentCommentId='';
  let currentMode='for-you';
  let allItems=[];
  let activeObserver=null;

  const demoItems=[
    {id:'demo_1',authorId:'bea-beauty',creator:'@bea.beauty',bio:'Beleza, skincare e autocuidado.',avatar:'https://i.pravatar.cc/96?img=47',caption:'Sérum Facial Hidratante. Resultado incrível ✨ #skincare #beleza',category:'Beleza',media:'https://storage.googleapis.com/coverr-main/mp4/Mt_Baker.mp4',mediaType:'video/mp4',likes:'12,3K',comments:'872',shares:'1,2K',product:{id:'kit-skincare',title:'Sérum Facial 30ml',price:'R$ 89,90',rating:'4,9',image:'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?auto=format&fit=crop&w=200&q=80'}},
    {id:'demo_2',authorId:'carros-motores',creator:'@carros.e.motores',bio:'Carros, motores e liberdade sobre rodas.',avatar:'https://i.pravatar.cc/96?img=13',caption:'Nada como liberdade sobre quatro rodas. 🔥🏁 #carros #lifestyle',category:'Automóveis',media:'https://storage.googleapis.com/coverr-main/mp4/Footboys.mp4',mediaType:'video/mp4',likes:'25,7K',comments:'512',shares:'2,1K'},
    {id:'demo_3',authorId:'casa-pratica',creator:'@casa.pratica',bio:'Ideias simples para uma casa mais prática.',avatar:'https://i.pravatar.cc/96?img=14',caption:'Uma ideia simples para deixar a casa mais organizada. ✨ #casa #organização',category:'Casa',media:'https://storage.googleapis.com/coverr-main/mp4/Night-Traffic.mp4',mediaType:'video/mp4',likes:'8,4K',comments:'204',shares:'630'}
  ];

  function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
  function readJson(key,fallback){try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback));}catch{return fallback;}}
  function writeJson(key,value){localStorage.setItem(key,JSON.stringify(value));}
  function readSocial(){const data=readJson(SOCIAL_KEY,{});return {likes:data.likes||{},favorites:data.favorites||{},comments:data.comments||{}};}
  function readFollows(){return readJson(FOLLOW_KEY,{});}
  function currentAuthorId(){try{return AP.publicationStore?.currentAuthor?.().authorId||'';}catch{return '';}}
  function isOwnItem(item){const authorId=currentAuthorId();return !!authorId&&item?.authorId===authorId;}
  function socialState(id){const data=readSocial();return {liked:!!data.likes[id],favorite:!!data.favorites[id],comments:data.comments[id]||[]};}
  function toggleSocial(type,id){const data=readSocial();data[type][id]=!data[type][id];if(!data[type][id])delete data[type][id];writeJson(SOCIAL_KEY,data);return !!data[type][id];}
  function ensureLiked(id){const data=readSocial();data.likes[id]=true;writeJson(SOCIAL_KEY,data);return true;}
  function toggleFollow(id){const data=readFollows();data[id]=!data[id];if(!data[id])delete data[id];writeJson(FOLLOW_KEY,data);return !!data[id];}
  function addComment(id,text){const data=readSocial();const list=data.comments[id]||(data.comments[id]=[]);const profile=readJson('ap:profile',{});list.unshift({id:`c_${Date.now()}`,name:profile.name||'Você',text:String(text).trim(),time:'Agora',img:profile.avatar||'https://i.pravatar.cc/80?img=47'});writeJson(SOCIAL_KEY,data);}
  function parseCount(value){if(typeof value==='number'&&Number.isFinite(value))return value;const raw=String(value??'0').trim().toUpperCase().replace(/\s/g,'');const suffix=raw.endsWith('K')?'K':raw.endsWith('M')?'M':'';const number=parseFloat(raw.replace(/[KM]/g,'').replace(/\./g,'').replace(',','.'));if(!Number.isFinite(number))return 0;return Math.round(number*(suffix==='K'?1000:suffix==='M'?1000000:1));}
  function formatCount(value){const count=Math.max(0,Number(value)||0);if(count>=1000000)return `${(count/1000000).toFixed(count>=10000000?0:1).replace('.',',').replace(',0','')}M`;if(count>=1000)return `${(count/1000).toFixed(count>=100000?0:1).replace('.',',').replace(',0','')}K`;return String(count);}
  function mediaTemplate(item,index){if(String(item.mediaType).startsWith('image/'))return `<img class="ap-feed-image" src="${esc(item.media)}" alt="${esc(item.title||item.caption)}">`;return `<video src="${esc(item.media)}" playsinline muted loop preload="${index<2?'auto':'metadata'}" ${index===0?'autoplay':''}></video>`;}
  function descriptionTemplate(item){const raw=item.title?item.title+' — '+item.caption:item.caption;const text=esc(raw);const long=String(raw).length>95;return `<p class="${long?'ap-description-collapsed':''}">${text}</p>${long?'<button type="button" class="ap-description-toggle" data-action="description-toggle">mais</button>':''}`;}
  function followButtonTemplate(item,following){if(isOwnItem(item)||following)return '';return '<button data-action="follow" class="ap-follow" aria-label="Seguir">+</button>';}
  function productId(item){return item?.product?.id||item?.productId||'';}
  function productLabel(item){return String(item?.productLabel||item?.product?.title||item?.product?.name||'Ver produto').slice(0,24);}
  function productButtonTemplate(item){const id=productId(item);if(!id)return '';return `<button class="ap-blue-bag" data-action="product" data-product-id="${esc(id)}"><span aria-hidden="true"></span><b>${esc(productLabel(item))}</b></button>`;}
  function slideTemplate(item,index){const social=socialState(item.id);const follows=readFollows();const base=parseCount(item.likes);const following=!!follows[item.authorId];return `<article class="ap-video-slide" data-id="${esc(item.id)}" data-author-id="${esc(item.authorId||'')}" data-base-likes="${base}">${mediaTemplate(item,index)}<div class="ap-like-burst">♥</div><div class="ap-play-indicator">▶</div><button class="ap-sound-toggle" data-action="sound">🔇</button><div class="ap-feed-top"><button class="ap-menu-icon" data-action="menu">☰</button><div class="ap-feed-tabs"><button class="${currentMode==='for-you'?'active':''}" data-action="feed-home">Para você</button><button class="${currentMode==='friends'?'active':''}" data-action="friends">Amigos</button></div><button class="ap-more" data-action="more">⋮</button></div><aside class="ap-actions"><div class="ap-action"><button data-action="like" class="${social.liked?'liked':''}">${social.liked?'♥':'♡'}</button><small data-like-count>${formatCount(base+(social.liked?1:0))}</small></div><div class="ap-action"><button data-action="comment">●</button><small>${social.comments.length||esc(item.comments||0)}</small></div><div class="ap-action"><button data-action="favorite" class="${social.favorite?'saved':''}">${social.favorite?'★':'☆'}</button><small>Salvar</small></div><div class="ap-action"><button data-action="share">↗</button><small>${esc(item.shares||0)}</small></div><div class="ap-avatar-wrap"><button class="ap-avatar-button" data-action="creator"><img class="ap-avatar" src="${esc(item.avatar)}" alt="Perfil"></button>${followButtonTemplate(item,following)}</div></aside><div class="ap-caption">${productButtonTemplate(item)}<button class="ap-creator-name" data-action="creator"><strong>${esc(item.creator)} <span class="ap-verified">✓</span></strong></button>${descriptionTemplate(item)}</div></article>`;}
  function friendsEmpty(){return `<section class="ap-friends-empty"><div>👥</div><h2>Seu feed de Amigos está vazio</h2><p>Siga pessoas para ver os vídeos delas aqui.</p><a href="app.html?view=search">Encontrar pessoas</a><nav class="ap-friends-top"><button data-action="feed-home">Para você</button><button class="active">Amigos</button></nav></section>`;}
  function ensureCommentsUI(){if(document.getElementById('apFeedComments'))return;document.body.insertAdjacentHTML('beforeend','<div id="apFeedCommentsBackdrop" class="ap-local-comments-backdrop"></div><section id="apFeedComments" class="ap-local-comments"><header><h2>Comentários</h2><button type="button">×</button></header><div id="apFeedCommentsList"></div><form><input placeholder="Adicionar comentário..." maxlength="280"><button>Enviar</button></form></section>');const close=()=>{document.getElementById('apFeedCommentsBackdrop').classList.remove('open');document.getElementById('apFeedComments').classList.remove('open');};document.querySelector('#apFeedComments header button').onclick=close;document.getElementById('apFeedCommentsBackdrop').onclick=close;document.querySelector('#apFeedComments form').onsubmit=event=>{event.preventDefault();const input=event.currentTarget.querySelector('input');const text=input.value.trim();if(!text||!currentCommentId)return;addComment(currentCommentId,text);input.value='';renderComments();const count=document.querySelector(`.ap-video-slide[data-id="${CSS.escape(currentCommentId)}"] [data-action="comment"]`)?.parentElement?.querySelector('small');if(count)count.textContent=String(socialState(currentCommentId).comments.length);};}
  function renderComments(){const host=document.getElementById('apFeedCommentsList');const comments=socialState(currentCommentId).comments;host.innerHTML=comments.length?comments.map(c=>`<article><img src="${esc(c.img)}" alt=""><div><strong>${esc(c.name)}</strong><p>${esc(c.text)}</p><small>${esc(c.time)}</small></div></article>`).join(''):'<p class="empty">Seja o primeiro a comentar.</p>';}
  function openComments(id){ensureCommentsUI();currentCommentId=id;renderComments();document.getElementById('apFeedCommentsBackdrop').classList.add('open');document.getElementById('apFeedComments').classList.add('open');document.querySelectorAll('.ap-video-slide video').forEach(v=>v.pause());}
  function setLiked(slide,liked){const button=slide.querySelector('[data-action="like"]');const count=slide.querySelector('[data-like-count]');const base=Number(slide.dataset.baseLikes)||0;button.textContent=liked?'♥':'♡';button.classList.toggle('liked',liked);if(count)count.textContent=formatCount(base+(liked?1:0));}
  function showBurst(slide){const burst=slide.querySelector('.ap-like-burst');burst.classList.remove('show');void burst.offsetWidth;burst.classList.add('show');}
  function showPlayState(slide,paused){const indicator=slide.querySelector('.ap-play-indicator');indicator.textContent=paused?'▶':'❚❚';indicator.classList.remove('show');void indicator.offsetWidth;indicator.classList.add('show');}
  function preloadNext(slide){const next=slide.nextElementSibling?.querySelector('video');if(next&&next.preload!=='auto'){next.preload='auto';next.load();}}
  async function loadItems(){try{const stored=await AP.publicationStore.listPublished();const local=stored.filter(item=>['video','image'].includes(item.type)&&item.privacy==='Público').map(AP.publicationStore.toViewModel);return [...local,...demoItems];}catch{return demoItems;}}
  function currentItems(){if(currentMode==='for-you')return allItems;const follows=readFollows();return allItems.filter(item=>follows[item.authorId]);}
  function observe(container){activeObserver?.disconnect();activeObserver=new IntersectionObserver(entries=>{entries.forEach(entry=>{const video=entry.target.querySelector('video');if(entry.isIntersecting&&entry.intersectionRatio>.72){container.querySelectorAll('video').forEach(v=>{if(v!==video)v.pause();});video?.play().catch(()=>{});preloadNext(entry.target);AP.events?.emit?.('feed:view',{contentId:entry.target.dataset.id,mode:currentMode});}else video?.pause();});},{threshold:[.72]});container.querySelectorAll('.ap-video-slide').forEach(slide=>activeObserver.observe(slide));}
  function mount(container){const items=currentItems();container.innerHTML=items.length?items.map(slideTemplate).join(''):friendsEmpty();observe(container);AP.appMenu?.mount();}
  async function render(container,items){allItems=items||await loadItems();mount(container);bind(container);}
  function bind(container){let lastTap=0;container.onclick=event=>{const actionButton=event.target.closest('[data-action]');const action=actionButton?.dataset.action;if(action==='feed-home'){currentMode='for-you';mount(container);return;}if(action==='friends'){currentMode='friends';mount(container);return;}const slide=event.target.closest('.ap-video-slide');if(!slide)return;const video=slide.querySelector('video');if(!actionButton){if(!video)return;const now=Date.now();if(now-lastTap<320){setLiked(slide,ensureLiked(slide.dataset.id));showBurst(slide);}else{if(video.paused){video.play().catch(()=>{});showPlayState(slide,false);}else{video.pause();showPlayState(slide,true);}}lastTap=now;return;}event.stopPropagation();const item=allItems.find(entry=>entry.id===slide.dataset.id);if(action==='menu'){AP.appMenu?.open();return;}if(action==='more')return;if(action==='like')setLiked(slide,toggleSocial('likes',slide.dataset.id));if(action==='favorite'){const saved=toggleSocial('favorites',slide.dataset.id);actionButton.textContent=saved?'★':'☆';actionButton.classList.toggle('saved',saved);}if(action==='comment')openComments(slide.dataset.id);if(action==='sound'&&video){video.muted=!video.muted;actionButton.textContent=video.muted?'🔇':'🔊';}if(action==='follow'){if(isOwnItem(item))return;const following=toggleFollow(slide.dataset.authorId);if(following)actionButton.remove();if(currentMode==='friends'&&!following)mount(container);}if(action==='description-toggle'){const p=actionButton.previousElementSibling;const expanded=p.classList.toggle('ap-description-expanded');p.classList.toggle('ap-description-collapsed',!expanded);actionButton.textContent=expanded?'menos':'mais';}if(action==='creator')AP.feedSheets?.openCreator({name:item?.creator,avatar:item?.avatar,bio:item?.bio});if(action==='product'){const id=actionButton.dataset.productId||productId(item);if(id)global.location.href=`app.html?view=product&product=${encodeURIComponent(id)}`;else global.location.href='app.html?view=shop';}if(action==='share'&&navigator.share)navigator.share({title:'AssistaPay',text:item?.caption||'Veja este conteúdo no AssistaPay',url:global.location.href}).catch(()=>{});};}
  AP.feedUI=Object.freeze({render,demoItems,loadItems,compatibility:FEED_COMPATIBILITY});
})(window);