(function(global){
  'use strict';
  const AP=global.AssistaPay=global.AssistaPay||{};

  const products=[
    {id:'smartwatch-x1',name:'Smartwatch X1',category:'Eletrônicos',price:'R$ 199,90',value:199.90,oldPrice:'R$ 249,90',rating:'4,8',sold:'3,2 mil vendidos',stock:2080,commission:12,approval:'auto',seller:'Tech Store',image:'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80',description:'Relógio inteligente com monitoramento de atividades, notificações e bateria de longa duração.'},
    {id:'kit-skincare',name:'Kit Skincare Completo',category:'Beleza',price:'R$ 129,90',value:129.90,oldPrice:'R$ 169,90',rating:'4,9',sold:'5,8 mil vendidos',stock:1540,commission:18,approval:'manual',seller:'Bella Care',image:'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?auto=format&fit=crop&w=800&q=80',description:'Rotina completa de cuidados com a pele para limpeza, hidratação e proteção.'},
    {id:'fone-bluetooth',name:'Fone Bluetooth Pro',category:'Eletrônicos',price:'R$ 129,90',value:129.90,oldPrice:'R$ 179,90',rating:'4,7',sold:'4,1 mil vendidos',stock:980,commission:10,approval:'auto',seller:'Audio Prime',image:'https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?auto=format&fit=crop&w=800&q=80',description:'Som potente, conexão estável e estojo com carregamento portátil.'},
    {id:'air-fryer',name:'Air Fryer 5L',category:'Casa',price:'R$ 299,90',value:299.90,oldPrice:'R$ 389,90',rating:'4,8',sold:'2,6 mil vendidos',stock:620,commission:8,approval:'manual',seller:'Casa Fácil',image:'https://images.unsplash.com/photo-1585515320310-259814833e62?auto=format&fit=crop&w=800&q=80',description:'Prepare refeições crocantes com menos óleo e mais praticidade.'}
  ];

  const money=value=>value.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
  const readCart=()=>{try{return JSON.parse(localStorage.getItem('ap:cart')||'[]');}catch{return[];}};
  const writeCart=cart=>localStorage.setItem('ap:cart',JSON.stringify(cart));
  const normalizeCart=()=>readCart().map(item=>typeof item==='string'?{id:item,qty:1}:item).filter(item=>products.some(product=>product.id===item.id)&&item.qty>0);
  const readAffiliate=()=>{try{return JSON.parse(localStorage.getItem('ap:affiliate-progress')||'null');}catch{return null;}};
  const readSeller=()=>{try{return JSON.parse(localStorage.getItem('ap:seller-account')||'null');}catch{return null;}};
  const readAffiliations=()=>{try{return JSON.parse(localStorage.getItem('ap:affiliations')||'[]');}catch{return[];}};
  const writeAffiliations=data=>localStorage.setItem('ap:affiliations',JSON.stringify(data));

  function accountState(){const affiliate=readAffiliate()||{};const seller=readSeller();return {affiliateUnlocked:affiliate.unlocked===true,sellerApproved:seller?.status==='approved'};}
  function affiliationFor(id){return readAffiliations().find(item=>item.productId===id);}
  function nav(active){return `<nav class="ap-page-nav"><a href="feed.html" class="${active==='home'?'active':''}"><span>⌂</span>Início</a><a href="app.html?view=search"><span>⌕</span>Pesquisar</a><a href="app.html?view=create" class="create ${active==='create'?'active':''}"><span>+</span></a><a href="app.html?view=messages"><span>✉</span>Mensagens</a><a href="app.html?view=profile" class="${active==='profile'?'active':''}"><span>♙</span>Perfil</a></nav>`;}
  function header(title,back='feed.html'){return `<header class="ap-page-header"><a href="${back}">‹</a><h1>${title}</h1><span></span></header>`;}
  function productCard(product){return `<button class="ap-card ap-product-card" data-product-id="${product.id}" data-category="${product.category}"><img src="${product.image}" alt="${product.name}"><div class="ap-card-body"><strong>${product.name}</strong><span class="ap-card-rating">★ ${product.rating} · ${product.sold}</span><b>${product.price}</b><del>${product.oldPrice}</del></div></button>`;}
  function shop(){return `<main class="ap-page">${header('Shop')}<div class="ap-shop-search"><input id="apShopSearch" class="ap-search-box" placeholder="Buscar produtos..."><span>⌕</span></div><div class="ap-chip-row" id="apShopCategories"><button class="ap-chip active" data-category="Todos">Todos</button><button class="ap-chip" data-category="Eletrônicos">Eletrônicos</button><button class="ap-chip" data-category="Beleza">Beleza</button><button class="ap-chip" data-category="Casa">Casa</button></div><div class="ap-product-grid" id="apProductGrid">${products.map(productCard).join('')}</div><div class="ap-empty-state" id="apShopEmpty">Nenhum produto encontrado.</div></main>${nav('shop')}`;}

  function affiliatePanel(product){const state=accountState();const affiliation=affiliationFor(product.id);const commissionValue=product.value*product.commission/100;let action='';if(!state.affiliateUnlocked)action='<button data-open-affiliate-progress class="ap-affiliate-main">Ver requisitos do programa</button>';else if(affiliation?.status==='approved')action=`<button data-link-product="${product.id}" class="ap-affiliate-main">Vincular ao meu próximo vídeo</button>`;else if(affiliation?.status==='pending')action='<button class="ap-affiliate-pending" disabled>Solicitação em análise</button>';else action=`<button data-join-affiliate="${product.id}" class="ap-affiliate-main">Quero divulgar este produto</button>`;return `<div class="ap-affiliate-backdrop" data-close-affiliate></div><section class="ap-affiliate-panel" id="apAffiliatePanel" aria-hidden="true"><div class="ap-affiliate-handle"></div><header><h2>Área do afiliado</h2><button data-close-affiliate>×</button></header><div class="ap-affiliate-product"><img src="${product.image}" alt="${product.name}"><div><strong>${product.name}</strong><small>${product.seller}</small></div></div><section class="ap-affiliate-earnings"><small>Você pode ganhar</small><strong>${money(commissionValue)} por venda</strong><span>${product.commission}% de comissão</span></section><div class="ap-affiliate-stats"><div><b>${product.stock.toLocaleString('pt-BR')}</b><small>Em estoque</small></div><div><b>${product.rating}</b><small>Avaliação</small></div><div><b>${product.approval==='auto'?'Automática':'Manual'}</b><small>Aprovação</small></div></div><section class="ap-affiliate-ideas"><h3>Ideias para vídeos</h3><ul><li>Mostre o produto em uso</li><li>Destaque o principal benefício</li><li>Faça uma comparação rápida</li></ul></section>${action}</section>`;}

  function productDetails(product){return `<main class="ap-page ap-product-page">${header('Produto','app.html?view=shop')}<img class="ap-product-main-image" src="${product.image}" alt="${product.name}"><section class="ap-product-info"><div class="ap-product-badges"><span>★ ${product.rating}</span><span>${product.sold}</span></div><h1>${product.name}</h1><small class="ap-product-seller">Vendido por ${product.seller}</small><div class="ap-product-price"><b>${product.price}</b><del>${product.oldPrice}</del></div><p>${product.description}</p><div class="ap-product-benefits"><span>✓ Compra segura</span><span>↺ 7 dias para devolver</span><span>🚚 Frete calculado no carrinho</span></div><button class="ap-open-affiliate" data-open-affiliate>💼 Quero divulgar este produto</button></section><div class="ap-product-fixed-actions"><button data-add-cart="${product.id}" class="ap-outline-btn">Adicionar ao carrinho</button><button data-buy-now="${product.id}" class="ap-gradient-btn">Comprar agora</button></div></main>${affiliatePanel(product)}`;}

  function cart(){const items=normalizeCart();if(!items.length)return `<main class="ap-page">${header('Carrinho','app.html?view=shop')}<section class="ap-cart-empty"><div>🛒</div><h2>Seu carrinho está vazio</h2><p>Adicione produtos para continuar.</p><a href="app.html?view=shop" class="ap-gradient-link">Ir para o Shop</a></section></main>${nav('shop')}`;const rows=items.map(item=>{const product=products.find(p=>p.id===item.id);return `<article class="ap-cart-item" data-cart-id="${item.id}"><img src="${product.image}" alt="${product.name}"><div class="ap-cart-copy"><strong>${product.name}</strong><small>${product.category}</small><b>${money(product.value*item.qty)}</b><div class="ap-qty"><button data-qty-minus="${item.id}">−</button><span>${item.qty}</span><button data-qty-plus="${item.id}">+</button></div></div><button class="ap-remove" data-remove-cart="${item.id}">×</button></article>`;}).join('');const subtotal=items.reduce((sum,item)=>sum+products.find(p=>p.id===item.id).value*item.qty,0);const shipping=subtotal>=200?0:19.90;return `<main class="ap-page ap-cart-page">${header('Carrinho','app.html?view=shop')}<section class="ap-cart-list">${rows}</section><section class="ap-cart-summary"><div><span>Subtotal</span><b>${money(subtotal)}</b></div><div><span>Frete</span><b>${shipping===0?'Grátis':money(shipping)}</b></div><div class="total"><span>Total</span><b>${money(subtotal+shipping)}</b></div></section><button class="ap-gradient-btn ap-checkout" data-checkout>Finalizar compra</button></main>${nav('shop')}`;}
  function wallet(){return `<main class="ap-page">${header('Carteira')}<section class="ap-wallet-card"><small>Saldo disponível</small><h2>R$ 1.256,80</h2></section></main>${nav('wallet')}`;}
  function profile(){return `<main class="ap-page">${header('Perfil')}<section class="ap-profile-card"><h2>Perfil</h2></section></main>${nav('profile')}`;}
  function create(){return `<main class="ap-page">${header('Criar')}<section class="ap-create-box"><h2>Criar conteúdo</h2></section></main>${nav('create')}`;}
  function applyShopFilter(container){const query=container.querySelector('#apShopSearch')?.value.trim().toLowerCase()||'';const active=container.querySelector('.ap-chip.active')?.dataset.category||'Todos';let visible=0;container.querySelectorAll('.ap-product-card').forEach(card=>{const product=products.find(item=>item.id===card.dataset.productId);const show=product.name.toLowerCase().includes(query)&&(active==='Todos'||product.category===active);card.hidden=!show;if(show)visible++;});container.querySelector('#apShopEmpty')?.classList.toggle('show',visible===0);}
  function addItem(id){const cart=normalizeCart();const existing=cart.find(item=>item.id===id);if(existing)existing.qty++;else cart.push({id,qty:1});writeCart(cart);}
  function updateQty(id,delta){const cart=normalizeCart();const item=cart.find(entry=>entry.id===id);if(!item)return;item.qty+=delta;writeCart(cart.filter(entry=>entry.qty>0));global.location.reload();}
  function joinAffiliate(product){const items=readAffiliations().filter(item=>item.productId!==product.id);const status=product.approval==='auto'?'approved':'pending';items.push({productId:product.id,status,commission:product.commission,joinedAt:new Date().toISOString()});writeAffiliations(items);global.location.reload();}
  function openAffiliate(container){container.querySelector('.ap-affiliate-backdrop')?.classList.add('open');const panel=container.querySelector('#apAffiliatePanel');panel?.classList.add('open');panel?.setAttribute('aria-hidden','false');}
  function closeAffiliate(container){container.querySelector('.ap-affiliate-backdrop')?.classList.remove('open');const panel=container.querySelector('#apAffiliatePanel');panel?.classList.remove('open');panel?.setAttribute('aria-hidden','true');}

  function render(container){const params=new URLSearchParams(global.location.search);const view=params.get('view')||'shop';const product=products.find(item=>item.id===params.get('product'));container.innerHTML=product?productDetails(product):view==='cart'?cart():view==='wallet'?wallet():view==='profile'?profile():view==='create'?create():shop();container.querySelector('#apShopSearch')?.addEventListener('input',()=>applyShopFilter(container));container.querySelector('#apShopCategories')?.addEventListener('click',event=>{const chip=event.target.closest('[data-category]');if(!chip)return;container.querySelectorAll('.ap-chip').forEach(item=>item.classList.remove('active'));chip.classList.add('active');applyShopFilter(container);});container.querySelector('#apProductGrid')?.addEventListener('click',event=>{const card=event.target.closest('[data-product-id]');if(card)global.location.href=`app.html?view=product&product=${card.dataset.productId}`;});container.querySelector('[data-add-cart]')?.addEventListener('click',event=>{addItem(event.currentTarget.dataset.addCart);event.currentTarget.textContent='Adicionado ✓';});container.querySelector('[data-buy-now]')?.addEventListener('click',event=>{writeCart([{id:event.currentTarget.dataset.buyNow,qty:1}]);global.location.href='app.html?view=cart';});container.addEventListener('click',event=>{if(event.target.closest('[data-open-affiliate]'))openAffiliate(container);if(event.target.closest('[data-close-affiliate]'))closeAffiliate(container);const join=event.target.closest('[data-join-affiliate]');if(join){const target=products.find(item=>item.id===join.dataset.joinAffiliate);joinAffiliate(target);}if(event.target.closest('[data-open-affiliate-progress]'))global.location.href='app.html?view=seller-center';const link=event.target.closest('[data-link-product]');if(link){localStorage.setItem('ap:selected-affiliate-product',link.dataset.linkProduct);global.location.href='app.html?view=create';}const plus=event.target.closest('[data-qty-plus]');if(plus)updateQty(plus.dataset.qtyPlus,1);const minus=event.target.closest('[data-qty-minus]');if(minus)updateQty(minus.dataset.qtyMinus,-1);const remove=event.target.closest('[data-remove-cart]');if(remove){writeCart(normalizeCart().filter(item=>item.id!==remove.dataset.removeCart));global.location.reload();}if(event.target.closest('[data-checkout]')){writeCart([]);container.innerHTML='<main class="ap-page"><section class="ap-cart-empty"><div>✓</div><h2>Pedido criado!</h2><p>Simulação concluída.</p><a href="feed.html" class="ap-gradient-link">Voltar ao início</a></section></main>';}});}

  AP.pagesUI=Object.freeze({render,products});
})(window);