(function(global){
  'use strict';
  const AP=global.AssistaPay=global.AssistaPay||{};

  const products=[
    {id:'smartwatch-x1',name:'Smartwatch X1',category:'Eletrônicos',price:'R$ 199,90',oldPrice:'R$ 249,90',rating:'4,8',sold:'3,2 mil vendidos',image:'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80',description:'Relógio inteligente com monitoramento de atividades, notificações e bateria de longa duração.'},
    {id:'kit-skincare',name:'Kit Skincare Completo',category:'Beleza',price:'R$ 129,90',oldPrice:'R$ 169,90',rating:'4,9',sold:'5,8 mil vendidos',image:'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?auto=format&fit=crop&w=800&q=80',description:'Rotina completa de cuidados com a pele para limpeza, hidratação e proteção.'},
    {id:'fone-bluetooth',name:'Fone Bluetooth Pro',category:'Eletrônicos',price:'R$ 129,90',oldPrice:'R$ 179,90',rating:'4,7',sold:'4,1 mil vendidos',image:'https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?auto=format&fit=crop&w=800&q=80',description:'Som potente, conexão estável e estojo com carregamento portátil.'},
    {id:'air-fryer',name:'Air Fryer 5L',category:'Casa',price:'R$ 299,90',oldPrice:'R$ 389,90',rating:'4,8',sold:'2,6 mil vendidos',image:'https://images.unsplash.com/photo-1585515320310-259814833e62?auto=format&fit=crop&w=800&q=80',description:'Prepare refeições crocantes com menos óleo e mais praticidade.'}
  ];

  function nav(active){return `<nav class="ap-page-nav"><a href="feed.html" class="${active==='home'?'active':''}"><span>⌂</span>Início</a><a href="app.html?view=shop" class="${active==='shop'?'active':''}"><span>▱</span>Shop</a><a href="app.html?view=create" class="create ${active==='create'?'active':''}"><span>+</span></a><a href="app.html?view=wallet" class="${active==='wallet'?'active':''}"><span>▤</span>Carteira</a><a href="app.html?view=profile" class="${active==='profile'?'active':''}"><span>♙</span>Perfil</a></nav>`;}
  function header(title,back='feed.html'){return `<header class="ap-page-header"><a href="${back}">‹</a><h1>${title}</h1><span></span></header>`;}
  function productCard(product){return `<button class="ap-card ap-product-card" data-product-id="${product.id}" data-category="${product.category}"><img src="${product.image}" alt="${product.name}"><div class="ap-card-body"><strong>${product.name}</strong><span class="ap-card-rating">★ ${product.rating} · ${product.sold}</span><b>${product.price}</b><del>${product.oldPrice}</del></div></button>`;}
  function shop(){return `<main class="ap-page">${header('Shop')}<div class="ap-shop-search"><input id="apShopSearch" class="ap-search-box" placeholder="Buscar produtos..."><span>⌕</span></div><div class="ap-chip-row" id="apShopCategories"><button class="ap-chip active" data-category="Todos">Todos</button><button class="ap-chip" data-category="Eletrônicos">Eletrônicos</button><button class="ap-chip" data-category="Beleza">Beleza</button><button class="ap-chip" data-category="Casa">Casa</button></div><div class="ap-product-grid" id="apProductGrid">${products.map(productCard).join('')}</div><div class="ap-empty-state" id="apShopEmpty">Nenhum produto encontrado.</div></main>${nav('shop')}`;}
  function productDetails(product){return `<main class="ap-page ap-product-page">${header('Produto','app.html?view=shop')}<img class="ap-product-main-image" src="${product.image}" alt="${product.name}"><section class="ap-product-info"><div class="ap-product-badges"><span>★ ${product.rating}</span><span>${product.sold}</span></div><h1>${product.name}</h1><div class="ap-product-price"><b>${product.price}</b><del>${product.oldPrice}</del></div><p>${product.description}</p><div class="ap-product-benefits"><span>✓ Compra segura</span><span>↺ 7 dias para devolver</span><span>🚚 Frete calculado no carrinho</span></div></section><div class="ap-product-fixed-actions"><button data-add-cart="${product.id}" class="ap-outline-btn">Adicionar</button><button data-buy-now="${product.id}" class="ap-gradient-btn">Comprar agora</button></div></main>`;}
  function wallet(){return `<main class="ap-page">${header('Carteira')}<section class="ap-wallet-card"><small>Saldo disponível</small><h2>R$ 1.256,80</h2></section><div class="ap-actions-row"><button>＋<br>Depositar</button><button>⇩<br>Sacar</button><button>▤<br>Extrato</button><button>•••<br>Mais</button></div><section class="ap-wallet-card"><small>Ganhos deste mês</small><h2>R$ 1.256,80</h2></section></main>${nav('wallet')}`;}
  function profile(){const account=AP.engine?.get?.('session')?.getCurrentAccount?.();return `<main class="ap-page">${header('Perfil')}<section class="ap-profile-card"><img src="https://i.pravatar.cc/160?img=47" alt="Perfil"><h2>${account?.name||'Ana Silva'}</h2><small>${account?.email||'@anasilva'}</small><div class="ap-profile-stats"><div><b>1.245</b><small>Pontos</small></div><div><b>R$ 1.256</b><small>Saldo</small></div><div><b>28</b><small>Conquistas</small></div></div><button class="ap-gradient-btn" id="apLogout">Sair da conta</button></section></main>${nav('profile')}`;}
  function create(){return `<main class="ap-page">${header('Criar')}<section class="ap-create-box"><div><div class="icon">＋</div><h2>Publique seu conteúdo</h2><p>Envie um vídeo ou imagem para anunciar.</p><button>Selecionar arquivo</button></div></section></main>${nav('create')}`;}

  function applyShopFilter(container){const query=container.querySelector('#apShopSearch')?.value.trim().toLowerCase()||'';const active=container.querySelector('.ap-chip.active')?.dataset.category||'Todos';let visible=0;container.querySelectorAll('.ap-product-card').forEach(card=>{const product=products.find(item=>item.id===card.dataset.productId);const matchesQuery=product.name.toLowerCase().includes(query);const matchesCategory=active==='Todos'||product.category===active;const show=matchesQuery&&matchesCategory;card.hidden=!show;if(show)visible++;});container.querySelector('#apShopEmpty')?.classList.toggle('show',visible===0);}

  function render(container){
    const params=new URLSearchParams(global.location.search);
    const view=params.get('view')||'shop';
    const product=products.find(item=>item.id===params.get('product'));
    container.innerHTML=product?productDetails(product):view==='wallet'?wallet():view==='profile'?profile():view==='create'?create():shop();

    container.querySelector('#apShopSearch')?.addEventListener('input',()=>applyShopFilter(container));
    container.querySelector('#apShopCategories')?.addEventListener('click',event=>{const chip=event.target.closest('[data-category]');if(!chip)return;container.querySelectorAll('.ap-chip').forEach(item=>item.classList.remove('active'));chip.classList.add('active');applyShopFilter(container);});
    container.querySelector('#apProductGrid')?.addEventListener('click',event=>{const card=event.target.closest('[data-product-id]');if(card)global.location.href=`app.html?view=product&product=${card.dataset.productId}`;});
    container.querySelector('[data-add-cart]')?.addEventListener('click',event=>{const id=event.currentTarget.dataset.addCart;const cart=JSON.parse(localStorage.getItem('ap:cart')||'[]');if(!cart.includes(id))cart.push(id);localStorage.setItem('ap:cart',JSON.stringify(cart));event.currentTarget.textContent='Adicionado ✓';});
    container.querySelector('[data-buy-now]')?.addEventListener('click',event=>{const id=event.currentTarget.dataset.buyNow;localStorage.setItem('ap:cart',JSON.stringify([id]));global.location.href='app.html?view=cart';});
    document.getElementById('apLogout')?.addEventListener('click',()=>{AP.engine?.get?.('auth-module')?.signOut?.();global.location.href='index.html';});
  }

  AP.pagesUI=Object.freeze({render,products});
})(window);