(function(global){
'use strict';
const AP=global.AssistaPay=global.AssistaPay||{};
const MAX_FILE=25*1024*1024;
let stream=null,recorder=null,chunks=[],recordTimer=0;
const readFile=file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(new Error('Não foi possível ler o arquivo.'));reader.onload=()=>resolve(String(reader.result||''));reader.readAsDataURL(file);});
const stopStream=()=>{stream?.getTracks?.().forEach(track=>track.stop());stream=null;clearTimeout(recordTimer);};
const author=()=>AP.publicationStore?.currentAuthor?.()||{};
function archiveStory(item){AP.storyArchive?.save?.(item);}
async function savePublication({kind,media,mediaType,description=''}){const createdAt=new Date().toISOString();const item={id:'pub_'+Date.now(),type:kind,description:String(description||'').trim(),media,mediaBlob:media,mediaType,status:'published',createdAt,expiresAt:kind==='story'?new Date(Date.now()+86400000).toISOString():null,...author()};await AP.publicationStore?.save?.(item);if(kind==='story')archiveStory(item);AP.accountHistory?.record?.(kind==='story'?'story.published':'publication.published',{label:kind==='story'?'Story publicado':'Publicação criada',details:item.description||'Sem legenda'});AP.avatarStory?.rebuild?.();return item;}
function render(container){
 let facing='environment',mode='story',captured=null,capturedType='image/jpeg';
 container.innerHTML=`<main class="ap-camera-create"><section class="ap-camera-stage"><video class="ap-camera-preview" autoplay muted playsinline></video><div class="ap-camera-overlay"></div><header class="ap-camera-top"><button type="button" data-close aria-label="Fechar">×</button><span class="ap-camera-status" data-status>Preparando câmera…</span><button type="button" data-camera-settings aria-label="Configurações">⚙</button></header><aside class="ap-camera-tools"><button class="ap-camera-tool" type="button" data-text><b>Aa</b><span>Criar</span></button><button class="ap-camera-tool" type="button" data-boomerang><b>∞</b><span>Boomerang</span></button><button class="ap-camera-tool" type="button" data-layout><b>▦</b><span>Layout</span></button></aside><div class="ap-camera-bottom"><label class="ap-camera-gallery" aria-label="Abrir galeria"><span>▧</span><input type="file" accept="image/*,video/*" hidden data-gallery></label><button class="ap-camera-capture" type="button" data-capture aria-label="Capturar"></button><button class="ap-camera-switch" type="button" data-switch aria-label="Trocar câmera">↻</button></div><p class="ap-camera-message" data-message hidden></p></section><nav class="ap-camera-modes"><button type="button" data-mode="post">POST</button><button type="button" data-mode="story" class="active">STORY</button><button type="button" data-mode="video">VÍDEO</button><button type="button" data-mode="product">PRODUTO</button></nav></main>`;
 const stage=container.querySelector('.ap-camera-stage'),video=container.querySelector('.ap-camera-preview'),status=container.querySelector('[data-status]'),message=container.querySelector('[data-message]'),capture=container.querySelector('[data-capture]');
 const showMessage=text=>{message.textContent=text;message.hidden=!text;};
 async function startCamera(){stopStream();stage.classList.toggle('is-front',facing==='user');try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:facing}},audio:mode==='video'||mode==='story'});video.srcObject=stream;status.textContent=facing==='user'?'Câmera frontal':'Câmera traseira';showMessage('');}catch(error){status.textContent='Câmera indisponível';showFallback(error?.name==='NotAllowedError'?'Permita o acesso à câmera nas configurações do navegador.':'Não foi possível abrir a câmera neste aparelho.');}}
 function showFallback(text){if(stage.querySelector('.ap-camera-fallback'))return;const fallback=document.createElement('section');fallback.className='ap-camera-fallback';fallback.innerHTML=`<strong>Câmera não disponível</strong><small>${text}</small><label>Escolher da galeria<input type="file" accept="image/*,video/*" hidden data-fallback-file></label><button type="button" data-retry>Tentar novamente</button>`;stage.appendChild(fallback);fallback.querySelector('[data-retry]').onclick=()=>{fallback.remove();startCamera();};fallback.querySelector('[data-fallback-file]').onchange=e=>handleFile(e.target.files?.[0]);}
 function openReview(media,type){captured=media;capturedType=type||'image/jpeg';const review=document.createElement('section');review.className='ap-camera-review';review.innerHTML=`<header><button type="button" data-retake>Refazer</button><button class="publish" type="button" data-publish>Publicar</button></header><div class="ap-camera-review-media">${String(capturedType).startsWith('video/')?`<video src="${captured}" controls playsinline></video>`:`<img src="${captured}" alt="Prévia">`}</div><div class="ap-camera-caption"><textarea maxlength="500" placeholder="Escreva uma legenda"></textarea></div>`;stage.appendChild(review);review.querySelector('[data-retake]').onclick=()=>review.remove();review.querySelector('[data-publish]').onclick=async event=>{event.currentTarget.disabled=true;try{await savePublication({kind:mode==='post'?'image':mode==='product'?'image':mode,media:captured,mediaType:capturedType,description:review.querySelector('textarea').value});showMessage(mode==='story'?'Story publicado por 24 horas.':'Publicação criada.');review.remove();setTimeout(()=>location.href='../feed.html',700);}catch(err){showMessage(err.message||'Não foi possível publicar.');event.currentTarget.disabled=false;}};}
 function takePhoto(){const canvas=document.createElement('canvas');canvas.width=video.videoWidth||720;canvas.height=video.videoHeight||1280;const ctx=canvas.getContext('2d');if(facing==='user'){ctx.translate(canvas.width,0);ctx.scale(-1,1);}ctx.drawImage(video,0,0,canvas.width,canvas.height);openReview(canvas.toDataURL('image/jpeg',.9),'image/jpeg');}
 function stopRecording(){if(recorder&&recorder.state!=='inactive')recorder.stop();clearTimeout(recordTimer);capture.classList.remove('recording');}
 function startRecording(){if(!stream)return;chunks=[];try{recorder=new MediaRecorder(stream,{mimeType:MediaRecorder.isTypeSupported('video/webm;codecs=vp9')?'video/webm;codecs=vp9':'video/webm'});recorder.ondataavailable=e=>{if(e.data?.size)chunks.push(e.data);};recorder.onstop=async()=>{const blob=new Blob(chunks,{type:recorder.mimeType||'video/webm'});if(blob.size>MAX_FILE){showMessage('O vídeo ficou maior que 25 MB. Grave um vídeo menor.');return;}openReview(await readFile(blob),blob.type);};recorder.start();capture.classList.add('recording');showMessage('Gravando… toque novamente para parar.');recordTimer=setTimeout(stopRecording,mode==='story'?60000:180000);}catch{showMessage('A gravação não é suportada neste navegador.');}}
 async function handleFile(file){if(!file)return;if(file.size>MAX_FILE){showMessage('O arquivo deve ter no máximo 25 MB.');return;}openReview(await readFile(file),file.type||'image/jpeg');}
 capture.onclick=()=>{if(mode==='video'||mode==='story'){if(recorder?.state==='recording')stopRecording();else startRecording();}else takePhoto();};
 container.querySelector('[data-switch]').onclick=()=>{facing=facing==='environment'?'user':'environment';startCamera();};
 container.querySelector('[data-gallery]').onchange=e=>handleFile(e.target.files?.[0]);
 container.querySelector('[data-close]').onclick=()=>{stopStream();location.href='../feed.html';};
 container.querySelectorAll('[data-mode]').forEach(button=>button.onclick=()=>{mode=button.dataset.mode;container.querySelectorAll('[data-mode]').forEach(item=>item.classList.toggle('active',item===button));showMessage(mode==='product'?'Capture uma foto do produto.':'');startCamera();});
 container.querySelector('[data-text]').onclick=()=>showMessage('Editor de texto será a próxima ferramenta desta tela.');
 container.querySelector('[data-boomerang]').onclick=()=>showMessage('Boomerang será adicionado na próxima etapa.');
 container.querySelector('[data-layout]').onclick=()=>showMessage('Layout será adicionado na próxima etapa.');
 container.querySelector('[data-camera-settings]').onclick=()=>showMessage('Use o botão ↻ para trocar de câmera.');
 global.addEventListener('pagehide',stopStream,{once:true});startCamera();
}
AP.createUI=Object.freeze({render});
})(window);