(function(global){
  'use strict';
  const AP=global.AssistaPay=global.AssistaPay||{};
  const KEY='ap:publications';
  const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]');}catch{return[];}};
  const write=data=>localStorage.setItem(KEY,JSON.stringify(data));
  const readSeller=()=>{try{return JSON.parse(localStorage.getItem('ap:seller-account')||'null');}catch{return null;}};
  const readAffiliate=()=>{try{return JSON.parse(localStorage.getItem('ap:affiliate-progress')||'null');}catch{return null;}};
  function nav(){return `<nav class="ap-page-nav"><a href="feed.html"><span>⌂</span>Início</a><a href="app.html?view=shop"><span>▱</span>Shop</a><a href="app.html?view=create" class="create active"><span>+</span></a><a href="app.html?view=wallet"><span>▤</span>Carteira</a><a href="app.html?view=profile"><span>♙</span>Perfil</a></nav>`;}
  function accountState(){const seller=readSeller();const affiliate=readAffiliate()||{};return {seller,sellerApproved:seller?.status==='approved',sellerPending:seller?.status==='pending',affiliateUnlocked:affiliate.unlocked===true};}
  function commercialOption(){const state=accountState();if(state.sellerApproved)return `<button data-create-type="product"><span>▱</span><strong>Cadastrar produto</strong><small>Publique no Shop</small></button>`;if(state.affiliateUnlocked)return `<button data-create-type="affiliate"><span>◈</span><strong>Divulgar produto</strong><small>Escolha uma oferta afiliada</small></button>`;if(state.sellerPending)return `<button data-create-type="seller-pending" class="locked"><span>⌛</span><strong>Cadastro em análise</strong><small>Aguarde a aprovação</small></button>`;return `<button data-create-type="affiliate-progress" class="locked"><span>↗</span><strong>Programa de Afiliados</strong><small>Veja seu progresso</small></button>`;}

  function render(container){container.innerHTML=`<main class="ap-page ap-create-page"><header class="ap-page-header"><a href="feed.html">‹</a><h1>Criar</h1><span></span></header><p class="ap-create-intro">O que você deseja publicar?</p><section class="ap-create-options"><button data-create-type="video"><span>🎬</span><strong>Vídeo</strong><small>Publique no feed</small></button><button data-create-type="image"><span>🖼</span><strong>Imagem</strong><small>Foto com legenda</small></button><button data-create-type="story"><span>◉</span><strong>Story</strong><small>Visível por 24 horas</small></button>${commercialOption()}</section><section class="ap-create-drafts"><header><h2>Rascunhos</h2><small id="apDraftCount">0</small></header><div id="apDraftList"></div></section></main>${nav()}<div class="ap-create-backdrop" id="apCreateBackdrop"></div><section class="ap-create-sheet" id="apCreateSheet"><div class="ap-create-handle"></div><header><h2 id="apCreateTitle"></h2><button data-create-close>×</button></header><div id="apCreateBody"></div></section>`;bind(container);renderDrafts(container);}

  function open(container,title,body){container.querySelector('#apCreateTitle').textContent=title;container.querySelector('#apCreateBody').innerHTML=body;container.querySelector('#apCreateBackdrop').classList.add('open');container.querySelector('#apCreateSheet').classList.add('open');}
  function close(container){container.querySelector('#apCreateBackdrop').classList.remove('open');container.querySelector('#apCreateSheet').classList.remove('open');}
  function baseForm(type,accept){return `<form class="ap-create-form" data-create-form="${type}"><label class="ap-create-drop"><input name="media" type="file" accept="${accept}" required><span>＋</span><strong>Selecionar arquivo</strong><small>Toque para escolher no celular</small></label><div class="ap-create-preview" data-create-preview></div><label>Legenda</label><textarea name="caption" maxlength="220" placeholder="Escreva uma legenda..."></textarea><label>Privacidade</label><select name="privacy"><option>Público</option><option>Somente seguidores</option><option>Privado</option></select><div class="ap-create-actions"><button type="button" data-save-draft>Salvar rascunho</button><button class="ap-gradient-btn">Publicar</button></div></form>`;}
  function productForm(){return `<form class="ap-create-form" data-create-form="product"><label class="ap-create-drop"><input name="media" type="file" accept="image/*" required><span>＋</span><strong>Foto do produto</strong><small>Escolha uma imagem</small></label><div class="ap-create-preview" data-create-preview></div><label>Nome do produto</label><input name="name" required placeholder="Ex.: Fone Bluetooth Pro"><label>Preço</label><input name="price" type="number" min="0.01" step="0.01" required placeholder="0,00"><label>Comissão para afiliados (%)</label><input name="commission" type="number" min="0" max="80" step="1" value="10"><label>Estoque</label><input name="stock" type="number" min="0" step="1" required value="1"><label>Descrição</label><textarea name="description" maxlength="300" placeholder="Descreva o produto"></textarea><label>Categoria</label><select name="category"><option>Eletrônicos</option><option>Beleza</option><option>Casa</option><option>Moda</option><option>Outros</option></select><div class="ap-create-actions"><button type="button" data-save-draft>Salvar rascunho</button><button class="ap-gradient-btn">Enviar produto</button></div></form>`;}
  function storyForm(){return `<form class="ap-create-form" data-create-form="story"><label class="ap-create-drop"><input name="media" type="file" accept="image/*,video/*" required><span>＋</span><strong>Selecionar story</strong><small>Imagem ou vídeo vertical</small></label><div class="ap-create-preview portrait" data-create-preview></div><label>Texto opcional</label><input name="caption" maxlength="80" placeholder="Adicione uma mensagem"><div class="ap-create-actions"><button type="button" data-save-draft>Salvar rascunho</button><button class="ap-gradient-btn">Publicar story</button></div></form>`;}
  function affiliatePanel(){return `<div class="ap-create-commercial-info"><div>◈</div><h3>Escolha produtos para divulgar</h3><p>Você verá produtos com comissão disponível e poderá vinculá-los aos seus vídeos.</p><button class="ap-gradient-btn" onclick="location.href='app.html?view=shop'">Explorar produtos</button></div>`;}
  function renderDrafts(container){const drafts=read().filter(item=>item.status==='draft');container.querySelector('#apDraftCount').textContent=drafts.length;container.querySelector('#apDraftList').innerHTML=drafts.length?drafts.map(item=>`<article class="ap-draft"><div><strong>${item.type}</strong><small>${item.title||item.caption||'Sem título'}</small></div><button data-delete-draft="${item.id}">×</button></article>`).join(''):'<p class="ap-no-drafts">Nenhum rascunho salvo.</p>';}
  function savePublication(form,status){const data=new FormData(form);const file=data.get('media');const type=form.dataset.createForm;const item={id:`pub_${Date.now()}`,type,status,createdAt:new Date().toISOString(),title:data.get('name')||'',caption:data.get('caption')||'',price:data.get('price')||'',commission:data.get('commission')||'',stock:data.get('stock')||'',category:data.get('category')||'',privacy:data.get('privacy')||'Público',fileName:file?.name||''};const items=read();items.unshift(item);write(items);return item;}

  function bind(container){container.querySelector('#apCreateBackdrop').addEventListener('click',()=>close(container));container.addEventListener('click',event=>{const option=event.target.closest('[data-create-type]');if(option){const type=option.dataset.createType;if(type==='video')open(container,'Publicar vídeo',baseForm('video','video/*'));if(type==='image')open(container,'Publicar imagem',baseForm('image','image/*'));if(type==='story')open(container,'Publicar story',storyForm());if(type==='product'&&accountState().sellerApproved)open(container,'Cadastrar produto',productForm());if(type==='affiliate'&&accountState().affiliateUnlocked)open(container,'Divulgar produto',affiliatePanel());if(type==='affiliate-progress')global.location.href='app.html?view=seller-center';if(type==='seller-pending')open(container,'Cadastro em análise','<div class="ap-create-commercial-info"><div>⌛</div><h3>Estamos analisando seus dados</h3><p>Você poderá cadastrar produtos depois da aprovação da conta de vendedor.</p><button class="ap-gradient-btn" onclick="location.href=\'app.html?view=seller-center\'">Ver status</button></div>');}if(event.target.closest('[data-create-close]'))close(container);const remove=event.target.closest('[data-delete-draft]');if(remove){write(read().filter(item=>item.id!==remove.dataset.deleteDraft));renderDrafts(container);}if(event.target.closest('[data-save-draft]')){const form=event.target.closest('form');if(!form)return;savePublication(form,'draft');close(container);renderDrafts(container);}});
    container.addEventListener('change',event=>{const input=event.target.closest('input[type="file"]');if(!input)return;const file=input.files?.[0];if(!file)return;const preview=input.closest('form').querySelector('[data-create-preview]');preview.innerHTML='';const url=URL.createObjectURL(file);const el=file.type.startsWith('video/')?document.createElement('video'):document.createElement('img');el.src=url;if(el.tagName==='VIDEO'){el.controls=true;el.muted=true;}preview.appendChild(el);});
    container.addEventListener('submit',event=>{const form=event.target.closest('[data-create-form]');if(!form)return;event.preventDefault();if(!form.reportValidity())return;if(form.dataset.createForm==='product'&&!accountState().sellerApproved)return;savePublication(form,form.dataset.createForm==='product'?'pending-review':'published');close(container);container.insertAdjacentHTML('beforeend',`<div class="ap-create-toast" id="apCreateToast">${form.dataset.createForm==='product'?'Produto enviado para análise':'Publicado com sucesso'} ✓</div>`);setTimeout(()=>container.querySelector('#apCreateToast')?.remove(),2200);renderDrafts(container);});}
  AP.createUI=Object.freeze({render});
})(window);