(function(global){
'use strict';
const AP=global.AssistaPay=global.AssistaPay||{};
const MAX_FILE=25*1024*1024;
const MIN_VIDEO_BYTES=4096;
let stream=null,recorder=null,chunks=[],recordTimer=0;
const readFile=file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(new Error('Não foi possível ler o arquivo.'));reader.onload=()=>resolve(String(reader.result||''));reader.readAsDataURL(file);});
const stopStream=()=>{stream?.getTracks?.().forEach(track=>track.stop());stream=null;clearTimeout(recordTimer);};
const author=()=>AP.publicationStore?.currentAuthor?.()||{};
function archiveStory(item){AP.storyArchive?.save?.(item);}
async function savePublication({kind,media,mediaType,description=''}){const createdAt=new Date().toISOString();const item={id:'pub_'+Date.now(),type:kind,description:String(description||'').trim(),media,mediaBlob:media,mediaType,status:'published',createdAt,expiresAt:kind==='story'?new Date(Date.now()+86400000).toISOString():null,...author()};await AP.publicationStore?.save?.(item);if(kind==='story')archiveStory(item);AP.accountHistory?.record?.(kind==='story'?'story.published':'publication.published',{label:kind==='story'?'Story publicado':'Publicação criada',details:item.description||'Sem legenda'});AP.avatarStory?.rebuild?.();return item;}
function videoMetadata(blob){return new Promise((resolve,reject)=>{const url=URL.createObjectURL(blob),probe=document.createElement('video');let settled=false;const done=(fn,value)=>{if(settled)return;settled=true;URL.revokeObjectURL(url);probe.removeAttribute('src');probe.load();fn(value);};const timeout=setTimeout(()=>done(reject,new Error('O vídeo não terminou de ser processado.')),7000);probe.preload='metadata';probe.muted=true;probe.playsInline=true;probe.onloadedmetadata=()=>{clearTimeout(timeout);const duration=Number(probe.duration||0);if(!Number.isFinite(duration)||duration<.15)return done(reject,new Error('A gravação ficou vazia. Grave novamente por alguns segundos.'));done(resolve,{duration,width:probe.videoWidth||0,height:probe.videoHeight||0});};probe.onerror=()=>{clearTimeout(timeout);done(reject,new Error('O arquivo de vídeo ficou corrompido. Tente gravar novamente.'));};probe.src=url;probe.load();});}
function preferredMime(){const options=['video/webm;codecs=vp8,opus','video/webm;codecs=vp8','video/webm','video/mp4'];return options.find(type=>global.MediaRecorder?.isTypeSupported?.(type))||'';}
function render(container){
 let facing='environment',mode='story',captured=null,capturedType='image/jpeg';
 container.innerHTML=`<main class="ap-camera-create"><section class="ap-camera-stage"><video class="ap-camera-preview" autoplay muted playsinline></video><div class="ap-camera-overlay"></div><header class="ap-camera-top"><button type="button" data-close aria-label="Fechar">×</button><span class="ap-camera-status" data-status>Preparando câmera…</span><button type="button" data-camera-settings aria-label="Configurações">⚙</button></header><aside class="ap-camera-tools"><button class="ap-camera-tool" type="button" data-text><b>Aa</b><span>Criar</span></button><button class="ap-camera-tool" type="button" data-boomerang><b>∞</b><span>Boomerang</span></button><button class="ap-camera-tool" type="button" data-layout><b>▦</b><span>Layout</span></button></aside><div class="ap-camera-bottom"><label class="ap-camera-gallery" aria-label="Abrir galeria"><span>▧</span><input type="file" accept="image/*,video/*" hidden data-gallery></label><button class="ap-camera-capture" type="button" data-capture aria-label="Capturar"></button><button class="ap-camera-switch" type="button" data-switch aria-label="Trocar câmera">↻</button></div><p class="ap-camera-message" data-message hidden></p></section><nav class="ap-camera-modes"><button type="button" data-mode="post">POST</button><button type="button" data-mode="story" class="active">STORY</button><button type="button" data-mode="video">VÍDEO</button><button type="button" data-mode="product">PRODUTO</button></nav></main>`;
 const stage=container.querySelector('.ap-camera-stage'),video=container.querySelector('.ap-camera-preview'),status=container.querySelector('[data-status]'),message=container.querySelector('[data-message]'),capture=container.querySelector('[data-capture]');
 const showMessage=text=>{message.textContent=text;message.hidden=!text;};
 async function startCamera(){stopStream();stage.classList.toggle('is-front',facing==='user');try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:facing},width:{ideal:720},height:{ideal:1280}},audio:mode==='video'||mode==='story'});video.srcObject=stream;await video.play().catch(()=>{});status.textContent=facing==='user'?'Câmera frontal':'Câmera traseira';showMessage('');}catch(error){status.textContent='Câmera indisponível';showFallback(error?.name==='NotAllowedError'?'Permita o acesso à câmera nas configurações do navegador.':'Não foi possível abrir a câmera neste aparelho.');}}
 function showFallback(text){if(stage.querySelector('.ap-camera-fallback'))return;const fallback=document.createElement('section');fallback.className='ap-camera-fallback';fallback.innerHTML=`<strong>Câmera não disponível</strong><small>${text}</small><label>Escolher da galeria<input type="file" accept="image/*,video/*" hidden data-fallback-file></label><button type="button" data-retry>Tentar novamente</button>`;stage.appendChild(fallback);fallback.querySelector('[data-retry]').onclick=()=>{fallback.remove();startCamera();};fallback.querySelector('[data-fallback-file]').onchange=e=>handleFile(e.target.files?.[0]);}
 function openReview(media,type){captured=media;capturedType=type||'image/jpeg';const review=document.createElement('section');review.className='ap-camera-review';review.innerHTML=`<header><button type="button" data-retake>Refazer</button><button class="publish" type="button" data-publish>Publicar</button></header><div class="ap-camera-review-media">${String(capturedType).startsWith('video/')?`<video src="${captured}" controls playsinline preload="metadata"></video>`:`<img src="${captured}" alt="Prévia">`}</div><div class="ap-camera-caption"><textarea maxlength="500" placeholder="Escreva uma legenda"></textarea></div>`;stage.appendChild(review);const preview=review.querySelector('video');if(preview){preview.addEventListener('error',()=>{showMessage('Não foi possível reproduzir este vídeo. Toque em Refazer.');review.querySelector('[data-publish]').disabled=true;},{once:true});preview.load();}review.querySelector('[data-retake]').onclick=()=>review.remove();review.querySelector('[data-publish]').onclick=async event=>{event.currentTarget.disabled=true;try{await savePublication({kind:mode==='post'?'image':mode==='product'?'image':mode,media:captured,mediaType:capturedType,description:review.querySelector('textarea').value});showMessage(mode==='story'?'Story publicado por 24 horas.':'Publicação criada.');review.remove();setTimeout(()=>location.href='../feed.html',700);}catch(err){showMessage(err.message||'Não foi possível publicar.');event.currentTarget.disabled=false;}};}
 function takePhoto(){if(!video.videoWidth||!video.videoHeight){showMessage('A câmera ainda está carregando. Tente novamente.');return;}const canvas=document.createElement('canvas');canvas.width=video.videoWidth;canvas.height=video.videoHeight;const ctx=canvas.getContext('2d');if(facing==='user'){ctx.translate(canvas.width,0);ctx.scale(-1,1);}ctx.drawImage(video,0,0,canvas.width,canvas.height);openReview(canvas.toDataURL('image/jpeg',.9),'image/jpeg');}
 function stopRecording(){if(!recorder||recorder.state==='inactive')return;clearTimeout(recordTimer);try{recorder.requestData?.();}catch{}setTimeout(()=>{try{if(recorder.state!=='inactive')recorder.stop();}catch{}},120);capture.classList.remove('recording');status.textContent='Processando vídeo…';}
 function startRecording(){if(!stream||!global.MediaRecorder){showMessage('A gravação não está disponível neste navegador.');return;}if(!stream.getVideoTracks().some(track=>track.readyState==='live')){showMessage('A câmera perdeu a conexão. Abra novamente e tente gravar.');return;}chunks=[];const mime=preferredMime();try{recorder=mime?new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:2500000}):new MediaRecorder(stream);recorder.ondataavailable=event=>{if(event.data&&event.data.size>0)chunks.push(event.data);};recorder.onerror=()=>{capture.classList.remove('recording');status.textContent='Falha na gravação';showMessage('Não foi possível gravar o vídeo. Tente novamente.');};recorder.onstop=async()=>{capture.classList.remove('recording');clearTimeout(recordTimer);try{const type=recorder.mimeType||mime||chunks[0]?.type||'video/webm';const blob=new Blob(chunks,{type});chunks=[];if(blob.size<MIN_VIDEO_BYTES)throw new Error('A gravação ficou vazia. Segure o botão por pelo menos 1 segundo.');if(blob.size>MAX_FILE)throw new Error('O vídeo ficou maior que 25 MB. Grave um vídeo menor.');await videoMetadata(blob);const dataUrl=await readFile(blob);openReview(dataUrl,blob.type||type);status.textContent=facing==='user'?'Câmera frontal':'Câmera traseira';showMessage('');}catch(error){status.textContent=facing==='user'?'Câmera frontal':'Câmera traseira';showMessage(error.message||'Não foi possível processar o vídeo. Tente novamente.');}};recorder.start(250);capture.classList.add('recording');status.textContent='Gravando';showMessage('Gravando… solte o botão para finalizar.');recordTimer=setTimeout(stopRecording,mode==='story'?60000:180000);}catch(error){showMessage('A gravação não é suportada neste navegador.');}}
 async function handleFile(file){if(!file)return;if(file.size>MAX_FILE){showMessage('O arquivo deve ter no máximo 25 MB.');return;}try{if(file.type.startsWith('video/'))await videoMetadata(file);openReview(await readFile(file),file.type||'image/jpeg');}catch(error){showMessage(error.message||'Não foi possível abrir este arquivo.');}}
 capture.onclick=()=>{if(mode==='video'||mode==='story'){if(recorder?.state==='recording')stopRecording();else startRecording();}else takePhoto();};
 container.querySelector('[data-switch]').onclick=()=>{if(recorder?.state==='recording')return;facing=facing==='environment'?'user':'environment';startCamera();};
 container.querySelector('[data-gallery]').onchange=e=>handleFile(e.target.files?.[0]);
 container.querySelector('[data-close]').onclick=()=>{if(recorder?.state==='recording')stopRecording();stopStream();location.href='../feed.html';};
 container.querySelectorAll('[data-mode]').forEach(button=>button.onclick=()=>{if(recorder?.state==='recording')return;mode=button.dataset.mode;container.querySelectorAll('[data-mode]').forEach(item=>item.classList.toggle('active',item===button));showMessage(mode==='product'?'Capture uma foto do produto.':'');startCamera();});
 container.querySelector('[data-text]').onclick=()=>showMessage('Editor de texto será a próxima ferramenta desta tela.');
 container.querySelector('[data-boomerang]').onclick=()=>showMessage('Boomerang será adicionado na próxima etapa.');
 container.querySelector('[data-layout]').onclick=()=>showMessage('Layout será adicionado na próxima etapa.');
 container.querySelector('[data-camera-settings]').onclick=()=>showMessage('Use o botão ↻ para trocar de câmera.');
 global.addEventListener('pagehide',stopStream,{once:true});startCamera();
}
AP.createUI=Object.freeze({render});
})(window);