(function(global){
'use strict';
const AP=global.AssistaPay=global.AssistaPay||{};
const KEYS={products:'ap:seller-products',orders:'ap:orders',commissions:'ap:commissions',processed:'ap:commerce-processed-orders'};
const ORDER_SOURCES=['ap:orders','ap:checkout-orders','ap:buyer-orders','ap:last-order'];
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback));}catch{return fallback;}};
const write=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
const number=value=>{if(typeof value==='number')return Number.isFinite(value)?value:0;const clean=String(value||'0').replace(/[^0-9,.-]/g,'').replace(/\.(?=.*\.)/g,'').replace(',','.');return Number(clean)||0;};
function normalizeItems(order){const source=Array.isArray(order.items)?order.items:Array.isArray(order.products)?order.products:order.product?[order.product]:[];return source.map((item,index)=>({productId:String(item.productId||item.id||item.product?.id||`item_${index}`),name:item.name||item.title||item.productName||item.product?.name||item.product?.title||'Produto',quantity:Math.max(1,Number(item.quantity||item.qty||1)),price:number(item.price||item.unitPrice||item.product?.price),affiliateId:item.affiliateId||item.referrerId||item.creatorId||order.affiliateId||order.referrerId||'',sellerId:item.sellerId||item.storeId||order.sellerId||''}));}
function normalizeOrder(raw,index=0){if(!raw||typeof raw!=='object')return null;const items=normalizeItems(raw);if(!items.length)return null;const createdAt=raw.createdAt||raw.date||new Date().toISOString();const id=String(raw.id||raw.orderId||raw.number||`PED-${new Date(createdAt).getTime()}-${index}`);const total=number(raw.total||raw.amount)||items.reduce((sum,item)=>sum+item.price*item.quantity,0);return {...raw,id,createdAt,status:raw.status||'paid',buyer:raw.buyer||raw.customer?.name||raw.address?.name||'Cliente',paymentMethod:raw.paymentMethod||raw.payment||'Não informado',total,items};}
function collectOrders(){const byId=new Map();ORDER_SOURCES.forEach(key=>{const value=read(key,key==='ap:last-order'?null:[]);const list=Array.isArray(value)?value:value?[value]:[];list.forEach((raw,index)=>{const order=normalizeOrder(raw,index);if(order)byId.set(order.id,{...(byId.get(order.id)||{}),...order});});});return [...byId.values()].sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));}
function applyStock(orders,products){const processed=new Set(read(KEYS.processed,[]));let changed=false;orders.forEach(order=>{if(processed.has(order.id)||['pending','cancelled'].includes(order.status))return;order.items.forEach(item=>{const product=products.find(p=>String(p.id)===String(item.productId));if(product){product.stock=Math.max(0,Number(product.stock||0)-item.quantity);changed=true;}});processed.add(order.id);});if(changed)write(KEYS.products,products);write(KEYS.processed,[...processed]);}
function buildCommissions(orders,products){const existing=read(KEYS.commissions,[]);const manual=existing.filter(row=>row.manual===true);const generated=[];orders.forEach(order=>order.items.forEach(item=>{if(!item.affiliateId)return;const product=products.find(p=>String(p.id)===String(item.productId));const rate=number(item.commissionRate||product?.commission||order.commissionRate);if(rate<=0)return;generated.push({id:`com_${order.id}_${item.productId}_${item.affiliateId}`,orderId:order.id,productId:item.productId,productName:item.name,affiliateId:item.affiliateId,rate,value:item.price*item.quantity*rate/100,status:order.status==='delivered'?'available':order.status==='cancelled'?'cancelled':'pending',createdAt:order.createdAt});}));write(KEYS.commissions,[...manual,...generated]);return generated;}
function sync(){const orders=collectOrders();if(!orders.length)return {orders:0};write(KEYS.orders,orders);const products=read(KEYS.products,[]);applyStock(orders,products);const commissions=buildCommissions(orders,products);global.dispatchEvent(new CustomEvent('ap:commerce-synced',{detail:{orders:orders.length,commissions:commissions.length}}));return {orders:orders.length,commissions:commissions.length};}
let timer=0;const schedule=()=>{clearTimeout(timer);timer=setTimeout(sync,80);};
global.addEventListener('storage',event=>{if(ORDER_SOURCES.includes(event.key)||event.key===KEYS.products)schedule();});
document.addEventListener('submit',event=>{if(event.target.closest('.ap-checkout-form,[data-checkout-form]'))setTimeout(sync,300);},true);
document.addEventListener('click',event=>{if(event.target.closest('[data-place-order],[data-checkout-confirm],.ap-checkout-submit'))setTimeout(sync,500);},true);
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',sync);else sync();
setInterval(sync,5000);
AP.commerceSync=Object.freeze({sync,collectOrders});
})(window);
