(function(global){
  'use strict';
  const AP=global.AssistaPay=global.AssistaPay||{};
  const KEY='ap:profile';

  function read(){const account=AP.engine?.get?.('session')?.getCurrentAccount?.()||{};try{const saved=JSON.parse(localStorage.getItem(KEY)||'null');if(saved)return {...defaults(account),...saved};}catch{}return defaults(account);}
  function defaults(account){const base=(account.name||'Usuário AssistaPay').trim();return {name:base,username:'@'+base.toLowerCase().replace(/[^a-z0-9]+/g,'.').replace(/^\.|\.$/g,''),bio:'Criando, descobrindo e ganhando com o AssistaPay.',avatar:'https://i.pravatar.cc/240?img=47',story:'',followers:1240,following:328,likes:18600};}
  function write(profile){localStorage.setItem(KEY,JSON.stringify(profile));}
  function nav(){return `<nav class="ap-page-nav"><a href="feed.html"><span>⌂</span>Início</a><a href="app.html?view=shop"><span>▱</span>Shop</a><a href="app.html?view=create" class="create"><span>+</span></a><a href="app.html?view=wallet"><span>▤</span>Carteira</a><a href="app.html?view=profile" class="active"><span>♙</span>Perfil</a></nav>`;}

  async function render(container){const p=read();container.innerHTML=`<main class="ap-page ap-profile-page"><header class="ap-profile-top"><a href="feed.html">‹</a><h1>Perfil</h1><button data-profile-settings>⚙</button></header><section class="ap-profile-hero"><button class="ap-profile-avatar-button ${p.story?'has-story':''}" data-profile-avatar><img src="${p.avatar}" alt="Foto de perfil"></button><h2>${p.name}</h2><span>${p.username}</span><p>${p.bio}</p><div class="ap-profile-counts"><button><b>${p.following}</b><small>Seguindo</small></button><button><b>${p.followers}</b><small>Seguidores</small></button><button><b>${p.likes}</b><small>Curtidas</small></button></div><div class="ap-profile-buttons"><button data-edit-profile>Editar perfil</button><button data-share-profile>Compartilhar</button></div></section><a class="ap-profile-seller-link" href="app.html?view=seller-center"><span>💼</span><div><strong>Centro do Vendedor</strong><small>Afiliados, vendas, comissões e cadastro CPF/CNPJ</small></div><b>›</b></a><nav class="ap-profile-tabs"><button class="active" data-profile-tab="videos">▦ Publicações</button><button data-profile-tab="products">▱ Produtos</button><button data-profile-tab="favorites">♡ Favoritos</button></nav><section class="ap-profile-content" id="apProfileContent"></section></main>${nav()}<div class="ap-profile-backdrop" id="apProfileBackdrop"></div><section class="ap-profile-sheet" id="apProfileSheet"><div class="ap-profile-handle"></div><header><h2 id="apProfileSheetTitle"></h2><button data-profile-close>×</button></header><div id="apProfileSheetBody"></div></section><div class="ap-profile-viewer" id="apProfileViewer" aria-hidden="true"><button data-viewer-close>×</button><div class="ap-story-progress" id="apStoryProgress"></div><div id="apProfileViewerMedia"></div><div class="ap-viewer-user"><img src="${p.avatar}" alt=""><span>${p.username}</span></div></div>`;bind(container);await showTab(container,'videos');}

  async function showTab(container,tab){container.querySelectorAll('[data-profile-tab]').forEach(btn=>btn.classList.toggle('active',btn.dataset.profileTab===tab));const content=container.querySelector('#apProfileContent');if(tab==='videos'){content.innerHTML='<div class="ap-profile-loading">Carregando publicações...</div>';const author=AP.publicationStore.currentAuthor();const items=(await AP.publicationStore.listByAuthor(author.authorId)).filter(item=>['video','image'].includes(item.type)&&item.status==='published');if(!items.length){content.innerHTML='<div class="ap-profile-empty"><div>▦</div><h3>Nenhuma publicação ainda</h3><p>Seus vídeos e imagens aparecerão aqui.</p><a href="app.html?view=create">Criar publicação</a></div>';return;}content.innerHTML=`<div class="ap-profile-grid">${items.map(item=>{const vm=AP.publicationStore.toViewModel(item);const preview=String(item.mediaType).startsWith('image/')?`<img src="${vm.media}" alt="${item.title||'Publicação'}">`:`<video src="${vm.media}" muted playsinline preload="metadata"></video><span class="ap-profile-play">▶</span>`;return `<article data-profile-publication="${item.id}" data-media-url="${vm.media}" data-media-type="${item.mediaType}">${preview}<small>▶ ${item.views||0}</small><button data-publication-menu="${item.id}">⋮</button></article>`;}).join('')}</div>`;}if(tab==='products')content.innerHTML='<div class="ap-profile-empty"><div>▱</div><h3>Nenhum produto publicado</h3><p>Seus produtos aparecerão aqui.</p><a href="app.html?view=seller-center">Abrir Centro do Vendedor</a></div>';if(tab==='favorites')content.innerHTML='<div class="ap-profile-empty"><div>♡</div><h3>Nenhum favorito ainda</h3><p>Salve vídeos e produtos para encontrar depois.</p></div>';}
  function open(container,title,body){container.querySelector('#apProfileSheetTitle').textContent=title;container.querySelector('#apProfileSheetBody').innerHTML=body;container.querySelector('#apProfileBackdrop').classList.add('open');container.querySelector('#apProfileSheet').classList.add('open');}
  function close(container){container.querySelector('#apProfileBackdrop').classList.remove('open');container.querySelector('#apProfileSheet').classList.remove('open');}
  function openViewer(container,src,type,isStory=false){const viewer=container.querySelector('#apProfileViewer');const host=container.querySelector('#apProfileViewerMedia');host.innerHTML='';const media=String(type).startsWith('video/')?document.createElement('video'):document.createElement('img');media.src=src;if(media.tagName==='VIDEO'){media.controls=true;media.autoplay=true;media.playsInline=true;}host.appendChild(media);container.querySelector('#apStoryProgress').classList.toggle('active',isStory);viewer.classList.add('open');viewer.setAttribute('aria-hidden','false');}
  function closeViewer(container){const viewer=container.querySelector('#apProfileViewer');viewer.querySelector('video')?.pause();viewer.classList.remove('open');viewer.setAttribute('aria-hidden','true');}
  function avatarMenu(){const p=read();return `<div class="ap-avatar-actions"><button data-view-photo>◉ <span>Ver foto</span></button>${p.story?'<button data-view-story>▶ <span>Ver story</span></button>':''}<button data-edit-profile>✎ <span>Editar foto ou story</span></button></div>`;}
  function publicationMenu(id){return `<div class="ap-avatar-actions"><button data-open-publication="${id}">▶ <span>Abrir publicação</span></button><button data-delete-publication="${id}" class="danger">× <span>Excluir publicação</span></button></div>`;}
  function editForm(){const p=read();return `<form class="ap-profile-form" id="apProfileForm"><div class="ap-avatar-upload"><img src="${p.avatar}" id="apAvatarPreview" alt="Prévia da foto"><label class="ap-upload-btn">Escolher foto<input id="apAvatarFile" type="file" accept="image/*" hidden></label><small>JPG, PNG ou WEBP.</small></div><div class="ap-story-upload"><strong>Story do perfil</strong>${p.story?`<img src="${p.story}" id="apStoryPreview" alt="Prévia do story">`:'<div id="apStoryPreview" class="ap-story-placeholder">Sem story ativo</div>'}<label class="ap-upload-btn">Escolher story<input id="apStoryFile" type="file" accept="image/*" hidden></label>${p.story?'<button type="button" class="ap-remove-story" data-remove-story>Remover story</button>':''}</div><label>Nome</label><input name="name" value="${p.name}" required><label>Nome de usuário</label><input name="username" value="${p.username}" required><label>Bio</label><textarea name="bio" maxlength="120">${p.bio}</textarea><button class="ap-gradient-btn">Salvar alterações</button></form>`;}
  function settings(){return `<div class="ap-profile-settings-list"><button onclick="location.href='app.html?view=seller-center'">Centro do Vendedor</button><button>Conta e segurança</button><button>Privacidade</button><button>Notificações</button><button>Compras e pedidos</button><button>Central de ajuda</button><button class="danger" data-profile-logout>Sair da conta</button></div>`;}
  function processImage(file,portrait=false){return new Promise((resolve,reject)=>{if(!file.type.startsWith('image/'))return reject(new Error('invalid'));if(file.size>10*1024*1024)return reject(new Error('large'));const reader=new FileReader();reader.onerror=reject;reader.onload=()=>{const image=new Image();image.onerror=reject;image.onload=()=>{const canvas=document.createElement('canvas');canvas.width=portrait?720:512;canvas.height=portrait?1280:512;const sourceRatio=image.width/image.height,targetRatio=canvas.width/canvas.height;let sw=image.width,sh=image.height,sx=0,sy=0;if(sourceRatio>targetRatio){sw=image.height*targetRatio;sx=(image.width-sw)/2;}else{sh=image.width/targetRatio;sy=(image.height-sh)/2;}canvas.getContext('2d').drawImage(image,sx,sy,sw,sh,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL('image/jpeg',.8));};image.src=reader.result;};reader.readAsDataURL(file);});}

  function bind(container){let pendingAvatar='',pendingStory=null;container.querySelector('#apProfileBackdrop').addEventListener('click',()=>close(container));container.addEventListener('click',async event=>{const tab=event.target.closest('[data-profile-tab]');if(tab)await showTab(container,tab.dataset.profileTab);const card=event.target.closest('[data-profile-publication]');if(card&&!event.target.closest('[data-publication-menu]'))openViewer(container,card.dataset.mediaUrl,card.dataset.mediaType);const menu=event.target.closest('[data-publication-menu]');if(menu){event.stopPropagation();open(container,'Publicação',publicationMenu(menu.dataset.publicationMenu));}const openPub=event.target.closest('[data-open-publication]');if(openPub){const item=await AP.publicationStore.get(openPub.dataset.openPublication);if(item){close(container);const vm=AP.publicationStore.toViewModel(item);openViewer(container,vm.media,item.mediaType);}}const del=event.target.closest('[data-delete-publication]');if(del){if(confirm('Excluir esta publicação?')){await AP.publicationStore.remove(del.dataset.deletePublication);close(container);await showTab(container,'videos');}}if(event.target.closest('[data-profile-avatar]'))open(container,'Foto do perfil',avatarMenu());if(event.target.closest('[data-view-photo]')){close(container);openViewer(container,read().avatar,'image/jpeg');}if(event.target.closest('[data-view-story]')){close(container);const story=read().story;if(story)openViewer(container,story,'image/jpeg',true);}if(event.target.closest('[data-viewer-close]'))closeViewer(container);if(event.target.closest('[data-edit-profile]')){pendingAvatar='';pendingStory=null;open(container,'Editar perfil',editForm());}if(event.target.closest('[data-remove-story]')){pendingStory='';container.querySelector('#apStoryPreview')?.replaceWith(Object.assign(document.createElement('div'),{id:'apStoryPreview',className:'ap-story-placeholder',textContent:'Story será removido ao salvar'}));event.target.remove();}if(event.target.closest('[data-profile-settings]'))open(container,'Configurações',settings());if(event.target.closest('[data-profile-close]'))close(container);if(event.target.closest('[data-profile-logout]')){AP.engine?.get?.('auth-module')?.signOut?.();global.location.href='index.html';}if(event.target.closest('[data-share-profile]')){const p=read();if(navigator.share)navigator.share({title:p.name,text:`Veja meu perfil ${p.username} no AssistaPay`,url:global.location.href}).catch(()=>{});}});
    container.addEventListener('change',async event=>{const file=event.target.files?.[0];if(!file)return;try{if(event.target.id==='apAvatarFile'){pendingAvatar=await processImage(file,false);container.querySelector('#apAvatarPreview').src=pendingAvatar;}if(event.target.id==='apStoryFile'){pendingStory=await processImage(file,true);const image=document.createElement('img');image.id='apStoryPreview';image.src=pendingStory;image.alt='Prévia do story';container.querySelector('#apStoryPreview').replaceWith(image);}}catch{alert('Não foi possível usar essa imagem.');}});
    container.addEventListener('submit',event=>{const form=event.target.closest('#apProfileForm');if(!form)return;event.preventDefault();const data=new FormData(form);const current=read();write({...current,name:String(data.get('name')).trim(),username:String(data.get('username')).trim(),bio:String(data.get('bio')).trim(),avatar:pendingAvatar||current.avatar,story:pendingStory===null?current.story:pendingStory});close(container);render(container);});}
  AP.profileUI=Object.freeze({render});
})(window);