(function(global){
  'use strict';
  const AP=global.AssistaPay=global.AssistaPay||{};
  let activeUserId='';

  function esc(value){return String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));}
  function user(userId){return AP.searchService?.getById(userId)||{id:userId,name:'Usuário AssistaPay',username:'@usuario',avatar:'https://i.pravatar.cc/96'};}
  function nav(){return `<nav class="ap-page-nav ap-messages-nav"><a href="feed.html"><span>⌂</span>Início</a><a href="app.html?view=search"><span>⌕</span>Pesquisar</a><a href="app.html?view=create" class="create"><span>+</span></a><a href="app.html?view=messages" class="active"><span>✉</span>Mensagens</a><a href="app.html?view=profile"><span>♙</span>Perfil</a></nav>`;}
  function threadCard(thread){const profile=user(thread.userId);return `<button class="ap-message-thread" data-open-thread="${esc(thread.userId)}"><img src="${esc(profile.avatar)}" alt="${esc(profile.name)}"><div><strong>${esc(profile.name)}</strong><p>${esc(thread.last?.text||'Inicie uma conversa')}</p></div><small>${esc(thread.last?.time||'')}</small></button>`;}
  function renderList(container){const threads=AP.messagesStore.listThreads();container.innerHTML=`<main class="ap-messages-page"><header><a href="feed.html">‹</a><h1>Mensagens</h1><button data-new-message>＋</button></header><div class="ap-messages-search"><span>⌕</span><input id="apMessagesSearch" placeholder="Pesquisar conversas"></div><section id="apThreadsList">${threads.length?threads.map(threadCard).join(''):'<div class="ap-messages-empty"><span>✉</span><h2>Nenhuma conversa</h2><p>Abra o perfil de alguém e toque em Mensagem.</p></div>'}</section></main>${nav()}<section class="ap-chat-view" id="apChatView" aria-hidden="true"></section>`;bind(container);const pending=localStorage.getItem('ap:pending-chat-user');if(pending){localStorage.removeItem('ap:pending-chat-user');openThread(container,pending);}}
  function renderMessages(userId){return AP.messagesStore.getThread(userId).map(message=>`<article class="${message.from==='me'?'mine':'theirs'}"><p>${esc(message.text)}</p><small>${esc(message.time)}</small></article>`).join('');}
  function openThread(container,userId){AP.messagesStore.ensureThread(userId);activeUserId=userId;const profile=user(userId);const host=container.querySelector('#apChatView');host.innerHTML=`<main><header><button data-close-chat>‹</button><button class="ap-chat-person" data-chat-profile="${esc(userId)}"><img src="${esc(profile.avatar)}" alt="${esc(profile.name)}"><div><strong>${esc(profile.name)}</strong><small>${esc(profile.username)}</small></div></button><button data-chat-more>⋮</button></header><section class="ap-chat-messages" id="apChatMessages">${renderMessages(userId)}</section><form class="ap-chat-form"><button type="button" data-chat-attach>＋</button><input id="apChatInput" maxlength="500" placeholder="Mensagem..."><button type="submit">Enviar</button></form></main>`;host.classList.add('open');host.setAttribute('aria-hidden','false');requestAnimationFrame(()=>{const messages=host.querySelector('#apChatMessages');messages.scrollTop=messages.scrollHeight;host.querySelector('#apChatInput')?.focus();});}
  function closeThread(container){const host=container.querySelector('#apChatView');host.classList.remove('open');host.setAttribute('aria-hidden','true');activeUserId='';const list=container.querySelector('#apThreadsList');if(list){const threads=AP.messagesStore.listThreads();list.innerHTML=threads.map(threadCard).join('');}}
  function bind(container){container.addEventListener('click',event=>{const thread=event.target.closest('[data-open-thread]');if(thread)openThread(container,thread.dataset.openThread);if(event.target.closest('[data-close-chat]'))closeThread(container);const profile=event.target.closest('[data-chat-profile]');if(profile)global.location.href=`app.html?view=search&user=${encodeURIComponent(profile.dataset.chatProfile)}`;if(event.target.closest('[data-new-message]'))global.location.href='app.html?view=search';});container.addEventListener('input',event=>{if(event.target.id!=='apMessagesSearch')return;const query=event.target.value.toLowerCase().trim();container.querySelectorAll('.ap-message-thread').forEach(card=>card.hidden=!card.textContent.toLowerCase().includes(query));});container.addEventListener('submit',event=>{if(!event.target.matches('.ap-chat-form'))return;event.preventDefault();const input=event.target.querySelector('#apChatInput');const message=AP.messagesStore.send(activeUserId,input.value);if(!message)return;input.value='';const host=container.querySelector('#apChatMessages');host.insertAdjacentHTML('beforeend',`<article class="mine"><p>${esc(message.text)}</p><small>${esc(message.time)}</small></article>`);host.scrollTop=host.scrollHeight;});}
  function render(container){renderList(container);}
  AP.messagesUI=Object.freeze({render,openThread});
})(window);