(function(global){
  'use strict';
  const AP=global.AssistaPay=global.AssistaPay||{};
  const KEY='ap:seller-account';
  const AFFILIATE_KEY='ap:affiliate-progress';
  const DEV_AUTO_APPROVAL=true;

  function readSeller(){try{return JSON.parse(localStorage.getItem(KEY)||'null');}catch{return null;}}
  function writeSeller(data){localStorage.setItem(KEY,JSON.stringify(data));}
  function readAffiliate(){try{return JSON.parse(localStorage.getItem(AFFILIATE_KEY)||'null');}catch{return null;}}
  function writeAffiliate(data){localStorage.setItem(AFFILIATE_KEY,JSON.stringify(data));}
  function defaultAffiliate(){return {followers:380,followersGoal:500,videos:4,videosGoal:5,accountDays:18,accountDaysGoal:15,profileComplete:true,noInfractions:true,creatorScore:58,creatorScoreGoal:60,unlocked:false};}
  function activateTestAccess(){const now=new Date().toISOString();const seller=readSeller()||{type:'cpf',document:'00000000000',name:'Vendedor de Teste',tradeName:'Loja de Teste',representative:'',phone:'',address:'Endereço de teste',submittedAt:now};writeSeller({...seller,status:'approved',approvedAt:now,approvalMode:'development'});writeAffiliate({...defaultAffiliate(),...(readAffiliate()||{}),unlocked:true,unlockedAt:now,approvalMode:'development'});}
  function applyDevelopmentAccess(){if(!DEV_AUTO_APPROVAL)return;const seller=readSeller();if(seller&&seller.status!=='approved')activateTestAccess();const affiliate={...defaultAffiliate(),...(readAffiliate()||{})};if(!affiliate.unlocked)writeAffiliate({...affiliate,unlocked:true,unlockedAt:new Date().toISOString(),approvalMode:'development'});}
  function nav(){return `<nav class="ap-page-nav"><a href="feed.html"><span>⌂</span>Início</a><a href="app.html?view=shop"><span>▱</span>Shop</a><a href="app.html?view=create" class="create"><span>+</span></a><a href="app.html?view=wallet"><span>▤</span>Carteira</a><a href="app.html?view=profile" class="active"><span>♙</span>Perfil</a></nav>`;}

  function render(container){
    applyDevelopmentAccess();
    const seller=readSeller();
    const affiliate={...defaultAffiliate(),...(readAffiliate()||{})};
    container.innerHTML=`<main class="ap-page ap-seller-page">
      <header class="ap-page-header"><a href="app.html?view=profile">‹</a><h1>Centro do Vendedor</h1><span></span></header>
      <section class="ap-seller-hero"><div><small>Sua conta pode crescer com você</small><h2>${seller?'Painel do Vendedor':'Comece a vender no AssistaPay'}</h2><p>${seller?'Gerencie sua operação comercial em um só lugar.':'Ative vendas como pessoa física ou empresa, sem criar outra conta.'}</p></div><span>💼</span></section>
      ${DEV_AUTO_APPROVAL?'<p class="ap-seller-legal">Modo de desenvolvimento: vendedor e afiliado são aprovados automaticamente para testes.</p>':''}
      ${seller?sellerDashboard(seller):sellerStart()}
      ${affiliateCard(affiliate)}
      <section class="ap-seller-links"><button data-seller-section="sales">▤ <span><strong>Minhas vendas</strong><small>Pedidos, receita e desempenho</small></span>›</button><button data-seller-section="commissions">◈ <span><strong>Minhas comissões</strong><small>Ganhos como afiliado</small></span>›</button><button data-seller-section="products">▱ <span><strong>Meus produtos</strong><small>Produtos próprios e afiliados</small></span>›</button></section>
    </main>${nav()}
    <div class="ap-seller-backdrop" id="apSellerBackdrop"></div><section class="ap-seller-sheet" id="apSellerSheet"><div class="ap-seller-handle"></div><header><h2 id="apSellerTitle"></h2><button data-seller-close>×</button></header><div id="apSellerBody"></div></section>`;
    bind(container);
  }

  function sellerStart(){return `<section class="ap-seller-choices"><button data-activate-test-seller><span>⚡</span><div><strong>Ativar vendedor de teste agora</strong><small>Libera vendedor e afiliado imediatamente</small></div>›</button><button data-seller-type="cpf"><span>👤</span><div><strong>Pessoa Física</strong><small>Quero vender usando meu CPF</small></div>›</button><button data-seller-type="cnpj"><span>🏢</span><div><strong>Empresa</strong><small>Quero vender usando meu CNPJ</small></div>›</button></section><p class="ap-seller-legal">Durante os testes, a ativação será imediata.</p>`;}
  function sellerDashboard(seller){return `<section class="ap-seller-status"><div><small>Tipo de conta</small><strong>${seller.type==='cpf'?'Pessoa Física (CPF)':'Empresa (CNPJ)'}</strong></div><div><small>Status</small><strong class="${seller.status}">${seller.status==='approved'?'Aprovado':'Em análise'}</strong></div><div><small>Documento</small><strong>${maskDoc(seller.document)}</strong></div><button data-go-create>Testar cadastro de produto</button><button data-seller-edit>Atualizar cadastro</button></section>`;}
  function affiliateCard(a){const checks=[a.followers>=a.followersGoal,a.videos>=a.videosGoal,a.accountDays>=a.accountDaysGoal,a.profileComplete,a.noInfractions,a.creatorScore>=a.creatorScoreGoal];const percent=Math.round(checks.filter(Boolean).length/checks.length*100);return `<section class="ap-affiliate-card"><header><div><small>Programa de Afiliados</small><h2>${a.unlocked?'Afiliado habilitado':'Seu progresso: '+percent+'%'}</h2></div><span>${a.unlocked?'✓':'↗'}</span></header><div class="ap-progress"><i style="width:${a.unlocked?100:percent}%"></i></div><ul><li class="${checks[0]?'done':''}">Seguidores <b>${a.followers}/${a.followersGoal}</b></li><li class="${checks[1]?'done':''}">Vídeos publicados <b>${a.videos}/${a.videosGoal}</b></li><li class="${checks[2]?'done':''}">Conta ativa <b>${a.accountDays}/${a.accountDaysGoal} dias</b></li><li class="${checks[5]?'done':''}">Índice do criador <b>${a.creatorScore}/${a.creatorScoreGoal}</b></li></ul><button data-affiliate-details>${a.unlocked?'Abrir Minha Vitrine':'Ver todos os requisitos'}</button></section>`;}

  function maskDoc(doc=''){const digits=doc.replace(/\D/g,'');if(digits.length===11)return `***.${digits.slice(3,6)}.${digits.slice(6,9)}-**`;if(digits.length===14)return `**.${digits.slice(2,5)}.${digits.slice(5,8)}/****-**`;return 'Documento informado';}
  function cpfForm(){return `<form class="ap-seller-form" data-seller-form="cpf"><label>Nome completo</label><input name="name" required><label>CPF</label><input name="document" inputmode="numeric" maxlength="14" required placeholder="000.000.000-00"><label>Data de nascimento</label><input name="birth" type="date" required><label>Telefone</label><input name="phone" type="tel" required><label>Endereço</label><input name="address" required><label class="ap-check"><input name="terms" type="checkbox" required> Confirmo que os dados são verdadeiros e aceito os termos do vendedor.</label><button class="ap-gradient-btn">Ativar conta de teste</button></form>`;}
  function cnpjForm(){return `<form class="ap-seller-form" data-seller-form="cnpj"><label>Razão social</label><input name="companyName" required><label>Nome fantasia</label><input name="tradeName"><label>CNPJ</label><input name="document" inputmode="numeric" maxlength="18" required placeholder="00.000.000/0000-00"><label>Representante legal</label><input name="representative" required><label>Telefone comercial</label><input name="phone" type="tel" required><label>Endereço comercial</label><input name="address" required><label class="ap-check"><input name="terms" type="checkbox" required> Confirmo que possuo poderes para representar a empresa e aceito os termos.</label><button class="ap-gradient-btn">Ativar conta de teste</button></form>`;}
  function open(container,title,body){container.querySelector('#apSellerTitle').textContent=title;container.querySelector('#apSellerBody').innerHTML=body;container.querySelector('#apSellerBackdrop').classList.add('open');container.querySelector('#apSellerSheet').classList.add('open');}
  function close(container){container.querySelector('#apSellerBackdrop').classList.remove('open');container.querySelector('#apSellerSheet').classList.remove('open');}

  function bind(container){container.querySelector('#apSellerBackdrop').addEventListener('click',()=>close(container));container.addEventListener('click',event=>{if(event.target.closest('[data-activate-test-seller]')){activateTestAccess();render(container);return;}if(event.target.closest('[data-go-create]')){global.location.href='app.html?view=create';return;}const type=event.target.closest('[data-seller-type]')?.dataset.sellerType;if(type)open(container,type==='cpf'?'Cadastro de Pessoa Física':'Cadastro de Empresa',type==='cpf'?cpfForm():cnpjForm());if(event.target.closest('[data-seller-close]'))close(container);if(event.target.closest('[data-affiliate-details]'))global.location.href='app.html?view=create';const section=event.target.closest('[data-seller-section]')?.dataset.sellerSection;if(section)open(container,'Em desenvolvimento','<div class="ap-seller-info"><p>Esta área já está reservada na arquitetura e será conectada aos dados reais nas próximas etapas.</p></div>');if(event.target.closest('[data-seller-edit]')){const seller=readSeller();open(container,'Atualizar cadastro',seller?.type==='cpf'?cpfForm():cnpjForm());}});
    container.addEventListener('submit',event=>{const form=event.target.closest('[data-seller-form]');if(!form)return;event.preventDefault();if(!form.reportValidity())return;const data=new FormData(form);const type=form.dataset.sellerForm;const seller={type,status:DEV_AUTO_APPROVAL?'approved':'pending',document:String(data.get('document')||''),name:String(data.get('name')||data.get('companyName')||''),tradeName:String(data.get('tradeName')||''),representative:String(data.get('representative')||''),phone:String(data.get('phone')||''),address:String(data.get('address')||''),submittedAt:new Date().toISOString(),approvedAt:DEV_AUTO_APPROVAL?new Date().toISOString():null,approvalMode:DEV_AUTO_APPROVAL?'development':'manual'};writeSeller(seller);writeAffiliate({...defaultAffiliate(),...(readAffiliate()||{}),unlocked:DEV_AUTO_APPROVAL});close(container);render(container);});}
  AP.sellerCenterUI=Object.freeze({render,developmentAutoApproval:DEV_AUTO_APPROVAL,activateTestAccess});
})(window);