(function(global){
'use strict';
const AP=global.AssistaPay=global.AssistaPay||{};
const K={products:'ap:seller-products',orders:'ap:orders',commissions:'ap:commissions',coupons:'ap:seller-coupons'};
const read=(k,f=[])=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f));}catch{return f;}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const labels={pending:'Aguardando pagamento',paid:'Pago',preparing:'Preparando',shipped:'Enviado',delivered:'Entregue',cancelled:'Cancelado',available:'Liberada'};
const menu=[
 ['overview','▦','Visão geral'],['orders','▤','Pedidos'],['commissions','◇','Comissões'],
 ['products','▱','Produtos'],['showcase','▰','Minha Vitrine'],['finance','R$','Financeiro'],
 ['customers','♙','Clientes'],['coupons','%','Cupons'],['reviews','☆','Avaliações'],['settings','⚙','Configurações']
];
function products(){return read(K.products,[]);}
function orders(){return read(K.orders,[]);}
function commissions(){return read(K.commissions,[]);}
function activeTab(){const t=new URLSearchParams(location.search).get('tab');return menu.some(x=>x[0]===t)?t:'overview';}
function shell(tab){return `<main class="ap-page ap-commerce-page"><header class="ap-page-header"><a href="../app.html?view=profile">‹</a><h1>Centro do Vendedor</h1><a href="../feed.html">⌂</a></header><section class="ap-commerce-menu">${menu.map(([id,icon,name])=>`<button class="${id===tab?'active':''}" data-seller-tab="${id}"><span>${icon}</span><small>${name}</small></button>`).join('')}</section><section id="apSellerContent"></section></main>`;}
function overview(){const p=products(),o=orders(),c=commissions();const revenue=o.filter(x=>!['pending','cancelled'].includes(x.status)).reduce((s,x)=>s+Number(x.total||0),0);const open=o.filter(x=>!['delivered','cancelled'].includes(x.status)).length;const stock=p.reduce((s,x)=>s+Number(x.stock||0),0);const available=c.filter(x=>x.status==='available').reduce((s,x)=>s+Number(x.value||0),0);return `<section class="ap-commerce-section"><header><div><h2>Visão geral</h2><small>Acompanhe sua operação</small></div></header><div class="ap-commerce-metrics"><article><small>Receita</small><strong>${money(revenue)}</strong></article><article><small>Pedidos ativos</small><strong>${open}</strong></article><article><small>Itens em estoque</small><strong>${stock}</strong></article><article><small>Comissões liberadas</small><strong>${money(available)}</strong></article></div><div class="ap-card"><h3>Ações rápidas</h3><p>Cadastre produtos, acompanhe pedidos e gerencie sua vitrine em um único lugar.</p><button data-seller-tab="products">Gerenciar produtos</button></div></section>`;}
function orderView(){const list=orders();return `<section class="ap-commerce-section"><header><div><h2>Pedidos</h2><small>${list.length} registrados</small></div></header>${list.length?`<div class="ap-commerce-list">${list.map(o=>`<article class="ap-order-card"><div><strong>${esc(o.id)}</strong><small>${esc(o.buyer||'Cliente')} · ${money(o.total)}</small><em>${labels[o.status]||o.status}</em></div><select data-order-status="${esc(o.id)}"><option value="paid" ${o.status==='paid'?'selected':''}>Pago</option><option value="preparing" ${o.status==='preparing'?'selected':''}>Preparando</option><option value="shipped" ${o.status==='shipped'?'selected':''}>Enviado</option><option value="delivered" ${o.status==='delivered'?'selected':''}>Entregue</option><option value="cancelled" ${o.status==='cancelled'?'selected':''}>Cancelado</option></select></article>`).join('')}</div>`:'<div class="ap-empty"><h3>Nenhum pedido</h3><p>As novas vendas aparecerão aqui.</p></div>'}</section>`;}
function commissionView(){const list=commissions();const pending=list.filter(x=>x.status!=='available').reduce((s,x)=>s+Number(x.value||0),0);const available=list.filter(x=>x.status==='available').reduce((s,x)=>s+Number(x.value||0),0);return `<section class="ap-commerce-section"><header><div><h2>Comissões</h2><small>Ganhos como afiliado</small></div></header><div class="ap-commerce-metrics"><article><small>Pendente</small><strong>${money(pending)}</strong></article><article><small>Disponível</small><strong>${money(available)}</strong></article></div>${list.length?`<div class="ap-commerce-list">${list.map(c=>`<article class="ap-order-card"><div><strong>${esc(c.productName||'Produto')}</strong><small>Pedido ${esc(c.orderId||'')}</small><em>${labels[c.status]||'Pendente'}</em></div><b>${money(c.value)}</b></article>`).join('')}</div>`:'<div class="ap-empty"><p>Nenhuma comissão registrada.</p></div>'}</section>`;}
function productView(){const list=products();return `<section class="ap-commerce-section"><header><div><h2>Produtos</h2><small>${list.length} cadastrados</small></div><button data-new-product>+ Novo</button></header>${list.length?`<div class="ap-commerce-list">${list.map(p=>`<article class="ap-commerce-card"><img src="${esc(p.image||'')}" alt=""><div><strong>${esc(p.name||'Produto')}</strong><small>${money(p.price)} · Estoque: ${Number(p.stock||0)}</small><em>${Number(p.commission||0)}% de comissão</em></div><button data-toggle-product="${esc(p.id)}">${p.status==='paused'?'Ativar':'Pausar'}</button></article>`).join('')}</div>`:'<div class="ap-empty"><h3>Nenhum produto</h3><button data-new-product>Cadastrar primeiro produto</button></div>'}</section>`;}
function showcaseView(){return `<section class="ap-commerce-section"><header><div><h2>Minha Vitrine</h2><small>Produtos afiliados e próprios</small></div></header><div class="ap-card"><p>Organize os produtos que seus seguidores verão no perfil.</p><a class="ap-gradient-btn" href="../app.html?view=showcase">Abrir Minha Vitrine</a></div></section>`;}
function financeView(){const o=orders();const received=o.filter(x=>x.status==='delivered').reduce((s,x)=>s+Number(x.total||0),0);const processing=o.filter(x=>['paid','preparing','shipped'].includes(x.status)).reduce((s,x)=>s+Number(x.total||0),0);return `<section class="ap-commerce-section"><header><div><h2>Financeiro</h2><small>Resumo dos recebimentos</small></div></header><div class="ap-commerce-metrics"><article><small>Recebido</small><strong>${money(received)}</strong></article><article><small>Em processamento</small><strong>${money(processing)}</strong></article></div><div class="ap-card"><p>O saque real será conectado ao provedor de pagamentos em uma etapa posterior.</p></div></section>`;}
function customersView(){const names=[...new Set(orders().map(x=>x.buyer).filter(Boolean))];return `<section class="ap-commerce-section"><header><div><h2>Clientes</h2><small>${names.length} compradores</small></div></header>${names.length?`<div class="ap-commerce-list">${names.map(n=>`<article class="ap-order-card"><strong>${esc(n)}</strong></article>`).join('')}</div>`:'<div class="ap-empty"><p>Nenhum cliente registrado.</p></div>'}</section>`;}
function couponsView(){const list=read(K.coupons,[]);return `<section class="ap-commerce-section"><header><div><h2>Cupons</h2><small>${list.length} ativos</small></div><button data-new-coupon>+ Criar</button></header>${list.length?`<div class="ap-commerce-list">${list.map(c=>`<article class="ap-order-card"><div><strong>${esc(c.code)}</strong><small>${Number(c.discount||0)}% de desconto</small></div></article>`).join('')}</div>`:'<div class="ap-empty"><p>Nenhum cupom criado.</p></div>'}</section>`;}
function simple(title,text){return `<section class="ap-commerce-section"><header><div><h2>${title}</h2></div></header><div class="ap-card"><p>${text}</p></div></section>`;}
function content(tab){return ({overview:overview(),orders:orderView(),commissions:commissionView(),products:productView(),showcase:showcaseView(),finance:financeView(),customers:customersView(),coupons:couponsView(),reviews:simple('Avaliações','As avaliações dos produtos aparecerão aqui após as primeiras entregas.'),settings:simple('Configurações','Dados da loja, frete, notificações e políticas serão configurados nesta área.')})[tab];}
function renderTab(container,tab){container.querySelectorAll('[data-seller-tab]').forEach(x=>x.classList.toggle('active',x.dataset.sellerTab===tab));container.querySelector('#apSellerContent').innerHTML=content(tab);}
function productForm(){return `<form class="ap-commerce-form"><h2>Novo produto</h2><input name="name" placeholder="Nome" required maxlength="80"><input name="price" type="number" step="0.01" min="0.01" placeholder="Preço" required><input name="stock" type="number" min="0" placeholder="Estoque" required><input name="commission" type="number" min="0" max="80" placeholder="Comissão %"><input name="image" placeholder="URL da imagem"><button>Salvar</button><button type="button" data-close-modal>Cancelar</button></form>`;}
function modal(container,html){container.insertAdjacentHTML('beforeend',`<div class="ap-commerce-backdrop open" id="apSellerModal"><section>${html}</section></div>`);}
function bind(container){container.addEventListener('click',e=>{const tab=e.target.closest('[data-seller-tab]');if(tab){const id=tab.dataset.sellerTab;history.replaceState(null,'',`../app.html?view=seller-center&tab=${id}`);renderTab(container,id);return;}if(e.target.closest('[data-new-product]'))modal(container,productForm());if(e.target.closest('[data-close-modal]'))container.querySelector('#apSellerModal')?.remove();const toggle=e.target.closest('[data-toggle-product]');if(toggle){const list=products(),p=list.find(x=>String(x.id)===toggle.dataset.toggleProduct);if(p)p.status=p.status==='paused'?'active':'paused';write(K.products,list);renderTab(container,'products');}if(e.target.closest('[data-new-coupon]')){const code=prompt('Código do cupom:');if(code){const discount=Number(prompt('Desconto em %:')||0);const list=read(K.coupons,[]);list.push({id:Date.now(),code:code.toUpperCase(),discount});write(K.coupons,list);renderTab(container,'coupons');}}});container.addEventListener('change',e=>{const s=e.target.closest('[data-order-status]');if(!s)return;const list=orders(),o=list.find(x=>String(x.id)===s.dataset.orderStatus);if(o)o.status=s.value;write(K.orders,list);AP.commerceSync?.sync?.();renderTab(container,'orders');});container.addEventListener('submit',e=>{const f=e.target.closest('.ap-commerce-form');if(!f)return;e.preventDefault();const d=new FormData(f),list=products();list.unshift({id:`prod_${Date.now()}`,name:String(d.get('name')),price:Number(d.get('price')),stock:Number(d.get('stock')),commission:Number(d.get('commission')||0),image:String(d.get('image')||''),status:'active'});write(K.products,list);container.querySelector('#apSellerModal')?.remove();renderTab(container,'products');});}
function render(container){const tab=activeTab();container.innerHTML=shell(tab);bind(container);renderTab(container,tab);return tab;}
AP.sellerCommerceUI=Object.freeze({render,products,orders,commissions});
})(window);