(function(global){
'use strict';
const AP=global.AssistaPay=global.AssistaPay||{};
const KEYS={products:'ap:seller-products',orders:'ap:orders',affiliations:'ap:affiliations',commissions:'ap:commissions'};
const read=(key,fallback=[])=>{try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback));}catch{return fallback;}};
const write=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function seller(){try{return JSON.parse(localStorage.getItem('ap:seller-account')||'null');}catch{return null;}}
function normalizeProducts(){const saved=read(KEYS.products,[]);if(saved.length)return saved;const demo=(AP.pagesUI?.products||[]).slice(0,3).map((p,i)=>({id:p.id||`seller_${i}`,name:p.name||p.title||'Produto',price:Number(String(p.price||'0').replace(/[^0-9,.-]/g,'').replace('.','').replace(',','.'))||0,stock:Number(p.stock??20),commission:Number(p.commission??10),status:'active',image:p.image||'',seller:p.seller||'Minha loja'}));write(KEYS.products,demo);return demo;}
function normalizeOrders(){const candidates=['ap:orders','ap:checkout-orders','ap:buyer-orders'];for(const key of candidates){const list=read(key,[]);if(Array.isArray(list)&&list.length){if(key!==KEYS.orders)write(KEYS.orders,list);return list;}}const products=normalizeProducts();const demo=products.length?[{id:'PED-TESTE-001',createdAt:new Date().toISOString(),status:'paid',buyer:'Cliente de teste',total:products[0].price||89.9,items:[{productId:products[0].id,name:products[0].name,quantity:1,price:products[0].price||89.9}],paymentMethod:'Pix'}]:[];write(KEYS.orders,demo);return demo;}
function commissions(){const current=read(KEYS.commissions,[]);if(current.length)return current;const orders=normalizeOrders();const products=normalizeProducts();const rows=[];orders.forEach(o=>(o.items||[]).forEach(item=>{const p=products.find(x=>x.id===item.productId);if(!p||!p.commission)return;rows.push({id:`com_${o.id}_${item.productId}`,orderId:o.id,productId:p.id,productName:p.name,value:(Number(item.price||p.price)*Number(item.quantity||1))*Number(p.commission)/100,status:o.status==='delivered'?'available':'pending',createdAt:o.createdAt});}));write(KEYS.commissions,rows);return rows;}
function statusLabel(s){return ({pending:'Aguardando pagamento',paid:'Pago',preparing:'Preparando',shipped:'Enviado',delivered:'Entregue',cancelled:'Cancelado',active:'Ativo',paused:'Pausado'}[s]||s||'Pendente');}
function nav(){return `<nav class="ap-page-nav"><a href="feed.html"><span>⌂</span>Início</a><a href="app.html?view=shop"><span>▱</span>Shop</a><a href="app.html?view=create" class="create"><span>+</span></a><a href="app.html?view=wallet"><span>▤</span>Carteira</a><a href="app.html?view=profile"><span>♙</span>Perfil</a></nav>`;}
function selectTab(container,name){const allowed=['products','orders','commissions'];const tab=allowed.includes(name)?name:'products';container.querySelectorAll('[data-commerce-tab]').forEach(b=>b.classList.toggle('active',b.dataset.commerceTab===tab));if(tab==='products')showProducts(container);if(tab==='orders')showOrders(container);if(tab==='commissions')showCommissions(container);}
function render(container){const account=seller();const products=normalizeProducts();const orders=normalizeOrders();const comm=commissions();const revenue=orders.filter(o=>!['cancelled','pending'].includes(o.status)).reduce((sum,o)=>sum+Number(o.total||0),0);const pending=orders.filter(o=>['paid','preparing'].includes(o.status)).length;const stock=products.reduce((sum,p)=>sum+Number(p.stock||0),0);const commissionTotal=comm.filter(c=>c.status==='available').reduce((s,c)=>s+Number(c.value||0),0);container.innerHTML=`<main class="ap-page ap-commerce-page"><header class="ap-page-header"><a href="app.html?view=profile">‹</a><h1>Painel do Vendedor</h1><button data-commerce-refresh>↻</button></header><section class="ap-commerce-hero"><div><small>${account?.tradeName||account?.name||'Loja de teste'}</small><h2>Visão geral da operação</h2><p>Produtos, estoque, pedidos e comissões em um só lugar.</p></div><span>💼</span></section><section class="ap-commerce-metrics"><article><small>Receita</small><strong>${money(revenue)}</strong></article><article><small>Pedidos ativos</small><strong>${pending}</strong></article><article><small>Itens em estoque</small><strong>${stock}</strong></article><article><small>Comissões liberadas</small><strong>${money(commissionTotal)}</strong></article></section><nav class="ap-commerce-tabs"><button data-commerce-tab="products">Produtos</button><button data-commerce-tab="orders">Pedidos</button><button data-commerce-tab="commissions">Comissões</button></nav><section id="apCommerceContent"></section></main>${nav()}`;bind(container);selectTab(container,new URLSearchParams(location.search).get('tab')||'products');}
function showProducts(container){const products=normalizeProducts();const host=container.querySelector('#apCommerceContent');host.innerHTML=`<section class="ap-commerce-section"><header><div><h2>Meus produtos</h2><small>${products.length} cadastrados</small></div><button data-new-product>+ Novo produto</button></header>${products.length?`<div class="ap-commerce-list">${products.map(p=>`<article class="ap-commerce-card"><img src="${esc(p.image||'https://via.placeholder.com/96')}" alt=""><div><strong>${esc(p.name)}</strong><small>${money(p.price)} · Estoque: ${p.stock}</small><em>${p.commission}% de comissão · ${statusLabel(p.status)}</em></div><div class="ap-commerce-actions"><button data-edit-product="${esc(p.id)}">Editar</button><button data-toggle-product="${esc(p.id)}">${p.status==='paused'?'Ativar':'Pausar'}</button></div></article>`).join('')}</div>`:'<div class="ap-commerce-empty">Nenhum produto cadastrado.</div>'}</section>`;}
function showOrders(container){const orders=normalizeOrders();const host=container.querySelector('#apCommerceContent');host.innerHTML=`<section class="ap-commerce-section"><header><div><h2>Minhas vendas</h2><small>${orders.length} pedidos</small></div></header>${orders.length?`<div class="ap-commerce-list">${orders.map(o=>`<article class="ap-order-card"><div><strong>${esc(o.id)}</strong><small>${esc(o.buyer||'Cliente')} · ${money(o.total)}</small><em>${statusLabel(o.status)}</em></div><select data-order-status="${esc(o.id)}"><option value="paid" ${o.status==='paid'?'selected':''}>Pago</option><option value="preparing" ${o.status==='preparing'?'selected':''}>Preparando</option><option value="shipped" ${o.status==='shipped'?'selected':''}>Enviado</option><option value="delivered" ${o.status==='delivered'?'selected':''}>Entregue</option><option value="cancelled" ${o.status==='cancelled'?'selected':''}>Cancelado</option></select></article>`).join('')}</div>`:'<div class="ap-commerce-empty">Nenhuma venda registrada.</div>'}</section>`;}
function showCommissions(container){const rows=commissions();const host=container.querySelector('#apCommerceContent');host.innerHTML=`<section class="ap-commerce-section"><header><div><h2>Minhas comissões</h2><small>Ganhos como afiliado</small></div></header>${rows.length?`<div class="ap-commerce-list">${rows.map(c=>`<article class="ap-order-card"><div><strong>${esc(c.productName)}</strong><small>Pedido ${esc(c.orderId)}</small><em>${c.status==='available'?'Liberada':'Pendente'}</em></div><b>${money(c.value)}</b></article>`).join('')}</div>`:'<div class="ap-commerce-empty">Nenhuma comissão registrada.</div>'}</section>`;}
function productForm(p={}){return `<form class="ap-commerce-form"><input type="hidden" name="id" value="${esc(p.id||'')}"><label>Nome</label><input name="name" value="${esc(p.name||'')}" required maxlength="80"><label>Preço</label><input name="price" type="number" step="0.01" min="0.01" value="${p.price||''}" required><label>Estoque</label><input name="stock" type="number" min="0" value="${p.stock??0}" required><label>Comissão (%)</label><input name="commission" type="number" min="0" max="80" value="${p.commission??10}"><label>URL da imagem</label><input name="image" value="${esc(p.image||'')}"><button class="ap-gradient-btn">Salvar produto</button></form>`;}
function openEditor(container,p){let modal=container.querySelector('#apCommerceModal');if(!modal){container.insertAdjacentHTML('beforeend','<div class="ap-commerce-backdrop" id="apCommerceModal"><section><header><h2>Produto</h2><button type="button" data-close-commerce>×</button></header><div id="apCommerceModalBody"></div></section></div>');modal=container.querySelector('#apCommerceModal');}modal.querySelector('#apCommerceModalBody').innerHTML=productForm(p);modal.classList.add('open');}
function bind(container){container.addEventListener('click',event=>{const tab=event.target.closest('[data-commerce-tab]');if(tab){history.replaceState(null,'',`app.html?view=seller-center&tab=${tab.dataset.commerceTab}`);selectTab(container,tab.dataset.commerceTab);}if(event.target.closest('[data-new-product]'))openEditor(container,{});const edit=event.target.closest('[data-edit-product]');if(edit)openEditor(container,normalizeProducts().find(p=>p.id===edit.dataset.editProduct)||{});const toggle=event.target.closest('[data-toggle-product]');if(toggle){const list=normalizeProducts();const p=list.find(x=>x.id===toggle.dataset.toggleProduct);if(p)p.status=p.status==='paused'?'active':'paused';write(KEYS.products,list);showProducts(container);}if(event.target.closest('[data-close-commerce]'))container.querySelector('#apCommerceModal')?.classList.remove('open');if(event.target.closest('[data-commerce-refresh]'))render(container);});container.addEventListener('change',event=>{const select=event.target.closest('[data-order-status]');if(!select)return;const orders=normalizeOrders();const order=orders.find(o=>o.id===select.dataset.orderStatus);if(order)order.status=select.value;write(KEYS.orders,orders);write(KEYS.commissions,[]);showOrders(container);});container.addEventListener('submit',event=>{const form=event.target.closest('.ap-commerce-form');if(!form)return;event.preventDefault();const data=new FormData(form);const list=normalizeProducts();const id=String(data.get('id')||`prod_${Date.now()}`);const current=list.find(p=>p.id===id);const product={id,name:String(data.get('name')||'').trim(),price:Number(data.get('price')),stock:Number(data.get('stock')),commission:Number(data.get('commission')||0),image:String(data.get('image')||''),status:current?.status||'active',seller:seller()?.tradeName||seller()?.name||'Minha loja'};const index=list.findIndex(p=>p.id===id);if(index>=0)list[index]=product;else list.unshift(product);write(KEYS.products,list);container.querySelector('#apCommerceModal')?.classList.remove('open');showProducts(container);});}
AP.sellerCommerceUI=Object.freeze({render,products:normalizeProducts,orders:normalizeOrders,commissions,selectTab});
})(window);