(function(global){
'use strict';
const AP=global.AssistaPay=global.AssistaPay||{};
const CART='ap:cart',ORDERS='ap:orders',ADDRESS='ap:checkout-address';
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f));}catch{return f;}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const products=()=>AP.pagesUI?.products||[];
function cart(){return read(CART,[]).map(i=>typeof i==='string'?{id:i,qty:1}:i).filter(i=>products().some(p=>p.id===i.id));}
function totals(items){const subtotal=items.reduce((s,i)=>s+(products().find(p=>p.id===i.id)?.value||0)*(i.qty||1),0);const discount=localStorage.getItem('ap:checkout-coupon')==='ASSISTA10'?Math.min(subtotal*.1,30):0;const shipping=subtotal>=200?0:19.9;return{subtotal,discount,shipping,total:subtotal-discount+shipping};}
function rows(items){return items.map(i=>{const p=products().find(x=>x.id===i.id);return `<article class="ap-checkout-item"><img src="${p.image}" alt="${p.name}"><div><strong>${p.name}</strong><small>${i.variant||'Padrão'} · Quantidade ${i.qty||1}</small><b>${money(p.value*(i.qty||1))}</b></div></article>`;}).join('');}
function render(container){const items=cart();if(!items.length){container.innerHTML='<main class="ap-page"><section class="ap-cart-empty"><div>🛒</div><h2>Carrinho vazio</h2><a class="ap-gradient-link" href="app.html?view=shop">Voltar ao Shop</a></section></main>';return;}const a=read(ADDRESS,{}),t=totals(items);container.innerHTML=`<main class="ap-page ap-checkout-page"><header class="ap-page-header"><a href="app.html?view=cart">‹</a><h1>Finalizar compra</h1><span></span></header><section class="ap-checkout-card"><h2>Endereço</h2><form id="apAddressForm" class="ap-address-form"><input name="name" value="${a.name||''}" placeholder="Nome completo" required><input name="cep" value="${a.cep||''}" placeholder="CEP" required><input name="street" value="${a.street||''}" placeholder="Rua" required><div><input name="number" value="${a.number||''}" placeholder="Número" required><input name="city" value="${a.city||''}" placeholder="Cidade" required></div></form></section><section class="ap-checkout-card"><h2>Produtos</h2>${rows(items)}</section><section class="ap-checkout-card"><h2>Cupom</h2><div class="ap-coupon-row"><input id="apCoupon" placeholder="ASSISTA10"><button data-coupon>Aplicar</button></div></section><section class="ap-checkout-card"><h2>Pagamento</h2><label class="ap-payment-option active"><input type="radio" name="pay" value="pix" checked> Pix</label><label class="ap-payment-option"><input type="radio" name="pay" value="card"> Cartão de crédito</label><label class="ap-payment-option"><input type="radio" name="pay" value="wallet"> Carteira AssistaPay</label></section><section class="ap-checkout-card ap-order-summary"><h2>Resumo</h2><div><span>Subtotal</span><b>${money(t.subtotal)}</b></div><div><span>Desconto</span><b>− ${money(t.discount)}</b></div><div><span>Frete</span><b>${t.shipping?money(t.shipping):'Grátis'}</b></div><div class="total"><span>Total</span><b>${money(t.total)}</b></div></section><button class="ap-gradient-btn ap-place-order" data-order>Fazer pedido · ${money(t.total)}</button></main>`;bind(container,items);}
function bind(container,items){container.querySelector('[data-coupon]').onclick=()=>{const value=container.querySelector('#apCoupon').value.trim().toUpperCase();value==='ASSISTA10'?localStorage.setItem('ap:checkout-coupon',value):localStorage.removeItem('ap:checkout-coupon');render(container);};container.querySelector('[data-order]').onclick=()=>{const form=container.querySelector('#apAddressForm');if(!form.reportValidity())return;const address=Object.fromEntries(new FormData(form));write(ADDRESS,address);const payment=container.querySelector('input[name="pay"]:checked').value;const t=totals(items),orders=read(ORDERS,[]);const order={id:`AP${Date.now().toString().slice(-8)}`,items,total:t.total,payment,status:payment==='pix'?'Aguardando pagamento':'Confirmado',address};orders.unshift(order);write(ORDERS,orders);write(CART,[]);localStorage.removeItem('ap:checkout-coupon');container.innerHTML=`<main class="ap-page"><section class="ap-order-success"><div>✓</div><h2>Pedido criado!</h2><p>Número: <strong>${order.id}</strong></p><a class="ap-gradient-link" href="feed.html">Voltar ao início</a></section></main>`;};}
function enhance(container){document.addEventListener('click',event=>{const buy=event.target.closest('[data-buy-now]');if(buy){event.preventDefault();event.stopImmediatePropagation();write(CART,[{id:buy.dataset.buyNow,qty:1}]);global.location.href='app.html?view=checkout';}const checkout=event.target.closest('[data-checkout]');if(checkout){event.preventDefault();event.stopImmediatePropagation();global.location.href='app.html?view=checkout';}},true);}
AP.checkoutUI=Object.freeze({render,enhance});
})(window);